### ISSUE TITLE
Problems with stable pyload branch

### ISSUE THREAD

**Issue by mbosner** [Gutz-Pilz/pyLoad-stuff#11]
This plugin does not work with the latest pyload stable branch ( https://github.com/pyload/pyload ).

https://github.com/vuolter said:

"This error come out when there are syntax error in the code, maybe result of the recent changes in SimpleCrypter plugin (upon which SerienjunkiesOrg is based)."

The issue:
https://github.com/pyload/pyload/issues/1002

I will clone the repository an put the latest (still broken) SerienjunkiesOrg.py into it (0.40) created by vuolter and uploaded into the forums. Sorry but i cannot fix it myself (yet).

**Comment by Gutz-Pilz** [comment]
xy
