### ISSUE TITLE
FileBot wird nicht ausgeführt

### ISSUE THREAD

**Issue by namealwaysinuse** [Gutz-Pilz/pyLoad-stuff#13]
Hallo,

nach dem letzten Update ist das Plugin ohne funktion :(

Der debug zeigt zwar, dass es geladen wird (beim start von pyload) aber es wird nicht mehr ausgelöst

**Comment by Gutz-Pilz** [comment]
jap. werde es fixen

**Comment by Gutz-Pilz** [comment]
https://github.com/Gutz-Pilz/pyLoad-stuff/blob/master/FileBot.py
^^pls try now

**Comment by namealwaysinuse** [comment]
Gibt es eine einfache möglichkeit zum update? Wenn ich das Plugin raus 
lösche ist es dennoch noch vorhanden und wenn ich es update dann bleibt 
dennoch die alte Version da :(


Am 6. Januar 2015 15:55:35 schrieb Gutz-Pilz <notifications@github.com>:

**Comment by Gutz-Pilz** [comment]
??
ich mach es immer so...in den hooks ordner wechseln und dort SJ.py und SJ.pyc löschen.
danach eine neue SJ.py datei erstellen und mit diesem inhalt füllen 
https://raw.githubusercontent.com/Gutz-Pilz/pyLoad-stuff/master/SJ.py

danach pyload neu starten und gut ist

**Comment by namealwaysinuse** [comment]
Lösch mal dir SJ.py und schau in deine pluginliste :D SJ müsste dennoch da 
sein :P

Ich downloads gerade mal was und teste dein Plugin.


Am 6. Januar 2015 16:32:56 schrieb Gutz-Pilz <notifications@github.com>:

**Comment by Gutz-Pilz** [comment]
ja. das ist nur ein überbleibsel. bedeutet nicht das es auch beim Start von pyload geladen wird...
Keine ahnung wie man das weg bekommt...
vlt in plugins.conf mal entsprechend die settings raus löschen.

spielt ja aber auch keine rolle. wenn du das plugin behalten willst einfach so machen wie beschrieben hab,

**Comment by Gutz-Pilz** [comment]
finktioniert es denn ?

**Comment by Gutz-Pilz** [comment]
Spätestens sonntag kommt eine funktionierende version

**Comment by namealwaysinuse** [comment]
Wie schauts aus? :D

**Comment by Gutz-Pilz** [comment]
müsste doch gehen...

**Comment by namealwaysinuse** [comment]
Du sagtest letztens, dass zum we eine neue Version kommt :P ich werde mal 
testen


Am 26. Januar 2015 10:50:44 schrieb Gutz-Pilz <notifications@github.com>:

**Comment by namealwaysinuse** [comment]
Grad nochmal getestet

Invalid Syntax line 12 steht im pyload log

**Comment by Gutz-Pilz** [comment]
komisch. line 12 hat kein code
https://raw.githubusercontent.com/Gutz-Pilz/pyLoad-stuff/master/FileBot.py
diese datei herunterladen oder eine erstellen und per copy paste den text einfügen

**Comment by feuerwasser85** [comment]
Hi, bevor ich jetzt einen neuen Issue aufmache, bei mir sagt Filebot:
DEBUG	FileBot-Hook: MKV-Checkup (archive_extracted)
DEBUG	Hier sind keine Archive
ERROR	FileBot: [Errno 13] Permission denied
DEBUG	All downloads finished

Wie kann ich FileBot die Permission geben? Bzw welche braucht er da? die vom File oder die vom Downloadverzeichnis?

**Comment by Gutz-Pilz** [comment]
chmod +x FileBoty.py
und dann pyload neu starten

2015-03-04 14:46 GMT+01:00 feuerwasser85 <notifications@github.com>:

**Comment by feuerwasser85** [comment]
hab ich gemacht, leider kein Erfolg.

**Comment by Gutz-Pilz** [comment]
welches OS hast du denn.
und in welchem ordner hast du dich befunden als du den Befehl ausgeführt hast ?

**Comment by feuerwasser85** [comment]
ich habe eine Synology DS1813+.
Pyload läuft unter /volume1/@appstore/pyload/
Das Configverzeichnis ist in /volume1/pyload
Das Filebot hook liegt in /volume1/pyload/userplugins/hooks
Die filebot.py hat 777 root:root
Der Pyload läuft unter dem user root

**Comment by Gutz-Pilz** [comment]
also hast du 
"chmod +x /volume1/pyload/userplugins/hooks/FileBot.py“
ausgeführt ?

**Comment by feuerwasser85** [comment]
ja

**Comment by namealwaysinuse** [comment]
Lösche die Datei

Geh in das hookverzeichnis

Sudo Touch filebot.py
Sudo nano filebot.py

Den raw Text von Pilz einfügen 

Von meinem iPhone gesendet

**Comment by Gutz-Pilz** [comment]
Okay, 
ich schau mal was sich machen lässt. ansonsten ist auch google dein freund und Helfer. 
ich hab mir python auch selbst beigebracht und komm eigtl aus einer ganz anderen branche

**Comment by feuerwasser85** [comment]
habe jetzt einiges versucht, leider ohne Erfolg.
Zum Verständnis: Hat Pyload keine Berechtigung oder FileBot?

**Comment by namealwaysinuse** [comment]
Vmtl FileBot, da das Script ja ausgeführt wird. 

Wenn du den Tipp mit Touch versucht hast dann liegt es aber an der Konfiguration von deiner DS...

Von meinem iPhone gesendet

**Comment by feuerwasser85** [comment]
Wo kann ich denn Filebot mehr Rechte geben? Das ist ja ne Java Applikation.
Ja, deinen Tipp hab ich sofort umgesetzt aber leider ohne Erfolg.

**Comment by namealwaysinuse** [comment]
Java? Dachte Python ;)

Vorher hast aber die filebot.py gelöscht oder?


Von meinem iPhone gesendet

**Comment by namealwaysinuse** [comment]
Da kommt mir was, stell mal im Pyload die Downloadrechte (für dl und danach) auf 777... Evtl bekommt filebot keinen Zugriff auf die Datei zum verschieben.

**Comment by feuerwasser85** [comment]
Filebot ist doch eine Java Applikation, das filebot.py ist ein Python Skript das den filebot ansteuert. Ich denke es hat etwas mit dem Filebot zu tun und nicht mit dem Plugin.
Auch das ändern der Rechte im Downloadverzeichnis hat leider nichts gebracht. Das Downloadverzeichnis hat 777 und alles darin auch. :-( ich verzweifle langsam. Hat denn dieses Problem sonst niemand?
