### ISSUE TITLE
HDafetcher all files marked as "already fetched"

### ISSUE THREAD

**Issue by feuerwasser85** [Gutz-Pilz/pyLoad-stuff#17]
Hi! All links in the HDAreaOrg plugin are marked as "already fetched" even new ones (as shown in the debug log). Is it a bug or is something wrong with my configuration? Does anyone else have this problem?
Anyway Thaks for the plugin!

**Comment by sixteeN11** [comment]
/////push
... already fetched

**Comment by Gutz-Pilz** [comment]
really!?
pls delete files.db and restart pyLoad in Debugmode - make sure to finish all packages before deleting "files.db"

**Comment by sixteeN11** [comment]
yes! it works. thx :)

**Comment by sixteeN11** [comment]
after 3 fetches the same failure.. "Already fetched"

**Comment by Gutz-Pilz** [comment]
sure. That happens after the interval is triggering the plugin again.
 i implemented that feature to make the plugin faster.
once the plugin processed a title it is marked "fetched" - next time it wont be scanned cause it was allready processed because it has the attribute "fetched". 
saves a lot of time because it wont be processed - means no stripping out of extra infos at imdb and so on.

if u deleted files.db it should've been no "already fetched" in debug output cause files.db stores "fetched" to each title

**Comment by feuerwasser85** [comment]
I've deleted the files.db 5 days ago and no movie was fetched since then. Have i something forgotten?

**Comment by Gutz-Pilz** [comment]
lass uns mal auf deutsch unterhalten...
habs grad selbst getestet

root@NAS:~# rm .pyload/files.db
root@NAS:~# pyLoadCore -d &
[1] 606
root@NAS:~# 606 (process ID) old priority 0, new priority 12
01.02.2015 12:41:12 INFO      starte pyLoad 0.4.9
01.02.2015 12:41:12 INFO      Benutze Home-Verzeichnis: /root/.pyload
01.02.2015 12:41:12 DEBUG     Deleting old pidfile pyload.pid
01.02.2015 12:41:12 DEBUG     Remote activated: True
01.02.2015 12:41:13 DEBUG     created index of plugins
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.hooks.PremiumizeMe -> userplugins.hooks.PremiumizeMe
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.internal.MultiHook -> userplugins.internal.MultiHook
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.hoster.PremiumizeMe -> userplugins.hoster.PremiumizeMe
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.internal.MultiHoster -> userplugins.internal.MultiHoster
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.internal.SimpleHoster -> userplugins.internal.SimpleHoster
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.hooks.Captcha9Kw -> userplugins.hooks.Captcha9Kw
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.hooks.ExtractArchive -> userplugins.hooks.ExtractArchive
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.internal.Extractor -> userplugins.internal.Extractor
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.internal.UnRar -> userplugins.internal.UnRar
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.internal.SevenZip -> userplugins.internal.SevenZip
01.02.2015 12:41:13 INFO      ExtractArchive: SevenZip ist nicht installiert
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.internal.UnZip -> userplugins.internal.UnZip
root@NAS:~# 01.02.2015 12:41:13 INFO      ExtractArchive: Aktiviert UnRar UnZip
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.hooks.JustPremium -> userplugins.hooks.JustPremium
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.hooks.UpdateManager -> userplugins.hooks.UpdateManager
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.hooks.SJ -> userplugins.hooks.SJ
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.hooks.UnSkipOnFail -> userplugins.hooks.UnSkipOnFail
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.hooks.XFileSharingPro -> userplugins.hooks.XFileSharingPro
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.hooks.FileBot -> userplugins.hooks.FileBot
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.hooks.HDAreaOrg -> userplugins.hooks.HDAreaOrg
01.02.2015 12:41:13 INFO      Aktivierte Plugins: Captcha9Kw, ExternalScripts, ExtractArchive, FileBot, HDAreaOrg, JustPremium, PremiumizeMe, SJ, UnSkipOnFail, UpdateManager, XFileSharingPro
01.02.2015 12:41:13 INFO      Deaktivierte Plugins: AlldebridCom, AndroidPhoneNotify, BypassCaptcha, CaptchaBrotherhood, Checksum, ClickAndLoad, DeathByCaptcha, DebridItaliaCom, DeleteFinished, DownloadScheduler, EasybytezCom, ExpertDecoders, FastixRu, FreeWayMe, HotFolder, IRCInterface, ImageTyperz, LinkdecrypterCom, LinksnappyCom, MegaDebridEu, MergeFiles, MultiHome, MultihostersCom, MultishareCz, MyfastfileCom, NoPremiumPl, OverLoadMe, PremiumTo, PutdriveCom, RPNetBiz, RapideoPl, RealdebridCom, RehostTo, RestartFailed, RestartSlow, SimplyPremiumCom, SimplydebridCom, SkipRev, SmoozedCom, UnrestrictLi, WindowsPhoneToastNotify, XMPPInterface, ZeveraCom
01.02.2015 12:41:13 INFO      Downloadzeit: True
01.02.2015 12:41:13 INFO      Starte ThriftBackend: 0.0.0.0:7227
01.02.2015 12:41:13 INFO      Starting builtin webserver: 0.0.0.0:8888
01.02.2015 12:41:13 INFO      Free space: 2.42 TiB
01.02.2015 12:41:13 INFO      Activating Accounts...
01.02.2015 12:41:13 DEBUG     Redirected import module.plugins.accounts.PremiumizeMe -> userplugins.accounts.PremiumizeMe
01.02.2015 12:41:14 DEBUG     PremiumizeMe: Get Account Info for 212269799
01.02.2015 12:41:15 DEBUG     PremiumizeMe: {u'status': 200, u'result': {u'trafficleft_gigabytes': 60.000086051412, u'trafficleft_bytes': 64424601837, u'expires': 1437914239, u'fairuse_left': 0.27272766387005, u'extuid': u'29bf6be1c4e376d156a6e9d75b9bbde1', u'type': u'premium', u'account_name': u'212269799'}, u'statusmessage': u'OK'}
01.02.2015 12:41:15 DEBUG     PremiumizeMe: Account Info: {'validuntil': 1437914239.0, 'trafficleft': 62914650}
01.02.2015 12:41:15 DEBUG     Redirected import module.plugins.accounts.UploadedTo -> userplugins.accounts.UploadedTo
01.02.2015 12:41:15 DEBUG     UploadedTo: Get Account Info for 13160018
01.02.2015 12:41:15 DEBUG     UploadedTo: Account Info: {'premium': True, 'validuntil': 1425303675.312973, 'trafficleft': 89611304.96}
01.02.2015 12:41:15 INFO      Activating Plugins...
01.02.2015 12:41:15 INFO      XFileSharingPro: Handling any hoster I can!
01.02.2015 12:41:15 DEBUG     XFileSharingPro: Loaded hoster pattern: https?://(?:www\.)?(?P<DOMAIN>[\w.^_]+(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
01.02.2015 12:41:15 INFO      XFileSharingPro: Handling any crypter I can!
01.02.2015 12:41:15 DEBUG     XFileSharingPro: Loaded crypter pattern: https?://(?:www\.)?(?P<DOMAIN>[\w.^_]+(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:user|folder)s?/\w+
01.02.2015 12:41:15 INFO      pyLoad is up and running
01.02.2015 12:41:17 INFO      PremiumizeMe: Reloading supported hoster list
01.02.2015 12:41:17 DEBUG     PremiumizeMe: Overwritten hosters: FilefactoryCom, FilepostCom, FilerNet, FilerioCom, FourSharedCom, HugefilesNet, LetitbitNet, NetloadIn, NowVideoSx, OneFichierCom, RapidgatorNet, StreamcloudEu, TurbobitNet, UploadableCh, UptoboxCom
01.02.2015 12:41:17 DEBUG     PremiumizeMe: New hosters: depfile.com, mixturecloud.com, movshare.net, novamov.com, purevid.com, salefiles.com, shareflare.net, uploadto.us, videoweed.es, vip-file.com
01.02.2015 12:41:17 DEBUG     PremiumizeMe: Regexp: .*(?P<DOMAIN>depfile\.com|mixturecloud\.com|movshare\.net|novamov\.com|purevid\.com|salefiles\.com|shareflare\.net|uploadto\.us|videoweed\.es|vip-file\.com).*
01.02.2015 12:41:31 DEBUG     SJFetcher - Abgelehnt: [ENGLISCH] The.Big.Bang.Theory.S08E13.The.Anxiety.Optimization.720p.WEB-DL.DD5.1.H.264-Oosh
01.02.2015 12:41:32 INFO      SJFetcher - NEW EPISODE: Boardwalk.Empire.S05E08.Eldorado.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP
01.02.2015 12:41:32 DEBUG     Redirected import module.plugins.crypter.SerienjunkiesOrg -> userplugins.crypter.SerienjunkiesOrg
01.02.2015 12:41:32 INFO      Added package Boardwalk.Empire.S05E08.Eldorado.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP containing 1 links
01.02.2015 12:41:32 INFO      SJFetcher - NEW EPISODE: Elementary.S03E12.720p.HDTV.X264-DIMENSION
01.02.2015 12:41:32 INFO      Added package Elementary.S03E12.720p.HDTV.X264-DIMENSION containing 1 links
01.02.2015 12:41:33 INFO      SJFetcher - NEW EPISODE: The.Big.Bang.Theory.S08E13.720p.HDTV.X264-DIMENSION
01.02.2015 12:41:33 INFO      Added package The.Big.Bang.Theory.S08E13.720p.HDTV.X264-DIMENSION containing 1 links
01.02.2015 12:41:33 DEBUG     SJFetcher - Abgelehnt: [ENGLISCH] Elementary.S03E11.720p.WEB-DL.DD5.1.H.264-NTb
01.02.2015 12:41:33 INFO      SJFetcher - NEW EPISODE: Boardwalk.Empire.S05E07.Ein.Kind.der.Suende.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP
01.02.2015 12:41:33 INFO      Added package Boardwalk.Empire.S05E07.Ein.Kind.der.Suende.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP containing 1 links
01.02.2015 12:41:33 INFO      SJFetcher - NEW EPISODE: Elementary.S03E11.720p.HDTV.X264-DIMENSION
01.02.2015 12:41:33 INFO      Added package Elementary.S03E11.720p.HDTV.X264-DIMENSION containing 1 links
01.02.2015 12:41:33 DEBUG     SJFetcher - Abgelehnt: [ENGLISCH] Elementary.S03E10.720p.WEB-DL.DD5.1.H.264-NTb
01.02.2015 12:41:34 INFO      SJFetcher - NEW EPISODE: Boardwalk.Empire.S05E06.Pakt.mit.dem.Teufel.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP
01.02.2015 12:41:34 INFO      Added package Boardwalk.Empire.S05E06.Pakt.mit.dem.Teufel.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP containing 1 links
01.02.2015 12:41:34 INFO      SJFetcher - NEW EPISODE: Elementary.S03E10.720p.HDTV.X264-DIMENSION
01.02.2015 12:41:34 INFO      Added package Elementary.S03E10.720p.HDTV.X264-DIMENSION containing 1 links
01.02.2015 12:41:34 DEBUG     SJFetcher - Abgelehnt: [ENGLISCH] Elementary.S03E05.E07.E08.720p.WEB-DL.DD5.1.H.264-NTb
01.02.2015 12:41:34 DEBUG     SJFetcher - Abgelehnt: [ENGLISCH] Elementary.S03E09.720p.WEB-DL.DD5.1.H.264-NTb
01.02.2015 12:41:34 DEBUG     SJFetcher - Abgelehnt: [ENGLISCH] New.Girl.S04E13.Coming.Out.720p.WEB-DL.DD5.1.H.264-SA89
01.02.2015 12:41:35 INFO      SJFetcher - NEW EPISODE: New.Girl.S04E13.720p.HDTV.X264-KILLERS
01.02.2015 12:41:35 INFO      Added package New.Girl.S04E13.720p.HDTV.X264-KILLERS containing 1 links
01.02.2015 12:41:35 DEBUG     SJFetcher - Abgelehnt: [DEUTSCH] The.Following.S02E15.Das.letzte.Abendmahl.German.DD51.Dubbed.DL.720p.BD.x264-TVS
01.02.2015 12:41:35 INFO      SJFetcher - NEW EPISODE: The.Following.S02E15.Das.letzte.Abendmahl.GERMAN.DUBBED.720p.BLURAY.x264-ZZGtv
01.02.2015 12:41:35 INFO      Added package The.Following.S02E15.Das.letzte.Abendmahl.GERMAN.DUBBED.720p.BLURAY.x264-ZZGtv containing 1 links
01.02.2015 12:41:35 DEBUG     SJFetcher - Abgelehnt: [DEUTSCH] Community.S05E13.Emotionale.Komponente.German.DD20.Dubbed.DL.720p.iTunesHD.AVC-TVS
01.02.2015 12:41:35 DEBUG     SJFetcher - Abgelehnt: [ENGLISCH] The.Big.Bang.Theory.S08E12.The.Space.Probe.Disintegration.720p.WEB-DL.DD5.1.H.264-Oosh
01.02.2015 12:41:42 INFO      HDaFetcher:	COLLECTOR: Sin City 2: A Dame to Kill For (2014) IMDb: 6.6
01.02.2015 12:41:42 DEBUG     Redirected import module.plugins.crypter.FilecryptCc -> userplugins.crypter.FilecryptCc
01.02.2015 12:41:42 INFO      Added package Sin City 2: A Dame to Kill For (2014) IMDb: 6.6 containing 1 links
01.02.2015 12:41:42 DEBUG     Redirected import module.plugins.internal.CaptchaService -> userplugins.internal.CaptchaService
01.02.2015 12:41:48 INFO      HDaFetcher:	COLLECTOR: Maze Runner - Die Auserwaehlten im Labyrinth (2014) IMDb: 6.9
01.02.2015 12:41:48 INFO      Added package Maze Runner - Die Auserwaehlten im Labyrinth (2014) IMDb: 6.9 containing 1 links
01.02.2015 12:41:58 INFO      HDaFetcher:	COLLECTOR: Amer (2009) IMDb: 6.3
01.02.2015 12:41:58 INFO      Added package Amer (2009) IMDb: 6.3 containing 1 links
01.02.2015 12:42:05 DEBUG     HDaFetcher:	Savages on Wolf Creek (2011) IMDb: 4.3: zu SCHLECHT
01.02.2015 12:42:13 INFO      HDaFetcher:	QUEUE: John Wick (2014) IMDb: 7.3
01.02.2015 12:42:13 INFO      Added package John Wick (2014) IMDb: 7.3 containing 1 links

**Comment by sixteeN11** [comment]
Bei mir läuft bis jetzt alles reibungslos. Hab den imdb Wert etwas runter gesetzt. Vielleicht versuchst du das mal?

**Comment by feuerwasser85** [comment]
in reject steht bei mir nichts, collector rating 6,5 queue rating 7,5, reject genre: documentary, resolution 1080p, min year 1990

**Comment by Gutz-Pilz** [comment]
probier mal das rating mit punkt zu trennen anstatt mit komma
also 6.5 und 7.5
dann wieder files.db löschen und pyload neu starten

**Comment by feuerwasser85** [comment]
ist das linkdecrypter plugin bei euch aktiviert?

**Comment by feuerwasser85** [comment]
danke, aber hab das vorhin nicht kopiert sondern nur abgeschrieben, die sind mit kommas getrennt

**Comment by Gutz-Pilz** [comment]
sollen ja aber mit punkt getrennt sein!

**Comment by Gutz-Pilz** [comment]
linkdecrypter dürfte keine rolle spielen. die packages sollten trotzdem hinzugefügt werden.
kannst du mal den log posten nach dem du files.db gepostet hast ?

**Comment by feuerwasser85** [comment]
bin jetzt so vorgegangen: files.db gelöscht, pyload neugestartet, hdareaorg plugin markiert alles als "already fetched" ohne irgendwelche fehlermeldungen.
ich werde das plugin mal löschen, die files.db löschen, hdarea in der plugin.conf löschen und das plugin neu erstellen, mal sehen was passiert.

**Comment by Gutz-Pilz** [comment]
guter plan. 
lösche auch mal HDareaFetched.pyc

**Comment by feuerwasser85** [comment]
wo finde ich die?

**Comment by Gutz-Pilz** [comment]
im hooks ordner

**Comment by feuerwasser85** [comment]
spannend, die datei existiert nicht und ist mir auch noch nie untergekommen, das SJ.py plugin hat eine .pyc

**Comment by Gutz-Pilz** [comment]
dann erstell die py mal komplett neu und geh so vor wie du beschrieben hast

**Comment by feuerwasser85** [comment]
45	01.02.2015 13:21:54	INFO	HDaFetcher:	COLLECTOR: Sin City 2: A Dame to Kill For (2014) IMDb: 6.6
46	01.02.2015 13:21:54	DEBUG	Redirected import module.plugins.crypter.FilecryptCc -> userplugins.crypter.FilecryptCc
47	01.02.2015 13:21:54	INFO	Added package Sin City 2: A Dame to Kill For (2014) IMDb: 6.6 containing 1 links
48	01.02.2015 13:21:54	DEBUG	Redirected import module.plugins.internal.CaptchaService -> userplugins.internal.CaptchaService
49	01.02.2015 13:22:00	INFO	HDaFetcher:	COLLECTOR: Maze Runner - Die Auserwaehlten im Labyrinth (2014) IMDb: 6.9
50	01.02.2015 13:22:00	INFO	Added package Maze Runner - Die Auserwaehlten im Labyrinth (2014) IMDb: 6.9 containing 1 links
51	01.02.2015 13:22:08	INFO	HDaFetcher:	COLLECTOR: Amer (2009) IMDb: 6.3
52	01.02.2015 13:22:09	INFO	Added package Amer (2009) IMDb: 6.3 containing 1 links
53	01.02.2015 13:22:14	DEBUG	HDaFetcher:	Repentance (2013) IMDb: 4.7: zu SCHLECHT
54	01.02.2015 13:22:21	DEBUG	HDaFetcher:	Savages on Wolf Creek (2011) IMDb: 4.3: zu SCHLECHT
143	01.02.2015 13:24:28	DEBUG	HDaFetcher:	The.Maze.Runner.2014.MULTi.COMPLETE.BLURAY-XORBiTANT... already fetched
144	01.02.2015 13:24:28	DEBUG	HDaFetcher:	Sin.City.2.A.Dame.to.Kill.For.German.DL.1080p.BluRay.x264.PROPER-EXQUiSiTE... already fetched
145	01.02.2015 13:24:28	DEBUG	HDaFetcher:	Sin.City.2.A.Dame.to.Kill.For.German.720p.BluRay.x264.PROPER-EXQUiSiTE... already fetched
146	01.02.2015 13:24:28	DEBUG	HDaFetcher:	Maze.Runner.Die.Auserwaehlten.im.Labyrinth.2014.German.DL.1080p.BluRay.AVC.REMUX-Leet... already fetched
147	01.02.2015 13:24:28	DEBUG	HDaFetcher:	Maze.Runner.Die.Auserwaehlten.im.Labyrinth.German.DL.1080p.BluRay.x264-EXQUiSiTE... already fetched
148	01.02.2015 13:24:28	DEBUG	HDaFetcher:	Maze.Runner.Die.Auserwaehlten.im.Labyrinth.German.720p.BluRay.x264-EXQUiSiTE... already fetched
149	01.02.2015 13:24:28	DEBUG	HDaFetcher:	Sin.City.A.Dame.to.Kill.For.2014.COMPLETE.BLURAY-SharpHD... already fetched
150	01.02.2015 13:24:28	DEBUG	HDaFetcher:	Ein.Sommer.in.der.Provence.2014.German.DTS-HD.DL.1080p.BluRay.AVC.Remux-HDA... already fetched
151	01.02.2015 13:24:28	DEBUG	HDaFetcher:	Ein.Sommer.in.der.Provence.2014.DUAL.COMPLETE.BLURAY-CWAHD... already fetched
152	01.02.2015 13:24:28	DEBUG	HDaFetcher:	Stonehearst.Asylum.Diese.Mauern.wirst.du.nie.verlassen.2014.German.DTS-HD.DL.1080p.Bl... already fetched
153	01.02.2015 13:24:30	DEBUG	HDaFetcher:	Eyeborgs.2009.German.DL.DTS.1080p.BluRay.x264-R0CKED... already fetched
154	01.02.2015 13:24:30	DEBUG	HDaFetcher:	Der.grosse.Gatsby.German.DTS.DL.1080p.BluRay-LeetHD... already fetched
155	01.02.2015 13:24:30	DEBUG	HDaFetcher:	Amer.2009.German.DTS.720p.BluRay.x264-LeetHD... already fetched
156	01.02.2015 13:24:30	DEBUG	HDaFetcher:	Repentance.Tag.der.Reue.2013.German.AC3.Dubbed.1080p.WebHD.x264-PixelHD... already fetched
157	01.02.2015 13:24:30	DEBUG	HDaFetcher:	Es.war.einmal.der.Mensch.DiSC.1+2.MULTi.COMPLETE.BLURAY-iFPD... already fetched
158	01.02.2015 13:24:30	DEBUG	HDaFetcher:	Savages.on.Wolf.Creek.Savages.Crossing.2011.DUAL.COMPLETE.BLURAY-CONFiDENCiAL... already fetched
159	01.02.2015 13:24:30	DEBUG	HDaFetcher:	The.Vortex.3D.2012.DUAL.COMPLETE.BLURAY-BDGRP... already fetched
160	01.02.2015 13:24:30	DEBUG	HDaFetcher:	Mystery.Train.1989.COMPLETE.BLURAY-iFPD... already fetched
161	01.02.2015 13:24:30	DEBUG	HDaFetcher:	Savages.on.Wolf.Creek.2011.German.DL.1080p.BluRay.x264-iMPERiUM... already fetched
162	01.02.2015 13:24:30	DEBUG	HDaFetcher:	Savages.on.Wolf.Creek.2011.German.720p.BluRay.x264-iMPERiUM... already fetched
163	01.02.2015 13:24:32	DEBUG	HDaFetcher:	John.Wick.German.DL.AC3.Dubbed.1080p.BluRay.x264.iNTERNAL-PsO... already fetched
164	01.02.2015 13:24:32	DEBUG	HDaFetcher:	John.Wick.German.DL.AC3.Dubbed.720p.BluRay.x264.iNTERNAL-PsO... already fetched
165	01.02.2015 13:24:32	DEBUG	HDaFetcher:	Nightcrawler.2014.German.AC3D.DL.1080p.BluRay.x264-PS... already fetched
166	01.02.2015 13:24:32	DEBUG	HDaFetcher:	Nightcrawler.2014.German.AC3D.DL.720p.BluRay.x264-PS... already fetched
167	01.02.2015 13:24:32	DEBUG	HDaFetcher:	John.Wick.2014.German.AC3D.DL.1080p.BluRay.x264-PS... already fetched
168	01.02.2015 13:24:32	DEBUG	HDaFetcher:	John.Wick.2014.German.AC3D.DL.720p.BluRay.x264-PS... already fetched
169	01.02.2015 13:24:32	DEBUG	HDaFetcher:	Nightcrawler.2014.German.AC3D.DL.720p.WEBHD.x264-PS... already fetched
170	01.02.2015 13:24:32	DEBUG	HDaFetcher:	Nightcrawler.2014.German.AC3D.DL.1080p.WEBHD.x264-PS... already fetched
171	01.02.2015 13:24:32	DEBUG	HDaFetcher:	96.Hours.-.Taken.3.German.DL.AC3.Dubbed.1080p.WebHD.h264-PsO... already fetched
172	01.02.2015 13:24:32	DEBUG	HDaFetcher:	96.Hours.-.Taken.3.German.DL.AC3.Dubbed.720p.WebHD.h264.iNTERNAL-PsO... already fetched
173	01.02.2015 13:24:34	DEBUG	HDaFetcher:	In.der.Glut.des.Suedens.1978.German.AC3D.DL.1080p.BluRay.x264-msd... already fetched
174	01.02.2015 13:24:34	DEBUG	HDaFetcher:	Arac.Attack.2002.German.DL.720p.HDTV.x264-msd... already fetched
175	01.02.2015 13:24:34	DEBUG	HDaFetcher:	Truth.or.Consequences.N.M.1997.German.AC3D.DL.1080p.BluRay.x264-msd... already fetched
176	01.02.2015 13:24:34	DEBUG	HDaFetcher:	I.Served.The.King.Of.England.2006.German.AC3D.720p.BluRay.x264-msd... already fetched
177	01.02.2015 13:24:34	DEBUG	HDaFetcher:	Inspector.Clouseau.Der.beste.Mann.bei.Interpol.German.DL.1976.HDTV.720p.x264.AC3-msd... already fetched
178	01.02.2015 13:24:34	DEBUG	HDaFetcher:	Mr.Deeds.geht.in.die.Stadt.1936.German.DL.720p.WEB-DL.h264-msd... already fetched
179	01.02.2015 13:24:34	DEBUG	HDaFetcher:	Top.Secret.1984.German.DL.720p.HDTV.x264-msd... already fetched
180	01.02.2015 13:24:34	DEBUG	HDaFetcher:	High.Crimes.2002.German.AC3D.DL.720p.BluRay.x264-msd... already fetched
181	01.02.2015 13:24:34	DEBUG	HDaFetcher:	Spione.Wie.Wir.1985.German.AC3D.DL.720p.Bluray.X264-msd... already fetched
182	01.02.2015 13:24:34	DEBUG	HDaFetcher:	Half.Light.Gefangen.zwischen.Licht.und.Schatten.2006.German.AC3D.DL.720p.BluRay.x264-... already fetched
183	01.02.2015 13:24:36	DEBUG	HDaFetcher:	Klick.2006.German.DL.AC3.1080p.BluRay.AVC.Remux-HDA... already fetched
184	01.02.2015 13:24:36	DEBUG	HDaFetcher:	Jurassic.Park.Ultimate.Trilogy.1993-2001.German.DTS.DL.1080p.BluRay.VC-1.Remux-DTSCre... already fetched
185	01.02.2015 13:24:36	DEBUG	HDaFetcher:	Rango.EXTENDED.2011.MULTi.COMPLETE.BLURAY-TRexHD... already fetched
186	01.02.2015 13:24:36	DEBUG	HDaFetcher:	Swing.Vote.Die.Beste.Wahl.2008.German.DTS.DL.1080p.BluRay.x264-SoW... already fetched
187	01.02.2015 13:24:36	DEBUG	HDaFetcher:	Superhero.Movie.Extended.Edition.2008.German.DTS.1080p.Bluray.x264.READ.NFO-w0rm... already fetched
188	01.02.2015 13:24:36	DEBUG	HDaFetcher:	Sunshine.Barry.und.die.Discowuermer.2008.German.DTS.DL.1080p.BluRay.x264-SoW... already fetched
189	01.02.2015 13:24:36	DEBUG	HDaFetcher:	Sunshine.Barry.und.die.Discowuermer.2008.German.DTS.720p.BluRay.x264-SoW... already fetched
190	01.02.2015 13:24:36	DEBUG	HDaFetcher:	Stomp.the.Yard.2007.1080p.BluRay.German.DL.x264-Hades... already fetched
191	01.02.2015 13:24:36	DEBUG	HDaFetcher:	Saw.IV.2007.UNRATED.German.DTS.DL.1080p.BluRay.x264-SightHD... already fetched
192	01.02.2015 13:24:36	DEBUG	HDaFetcher:	Saw.IV.2007.UNRATED.German.720p.BLURAY.x264.READ.NFO-LoveHD... already fetched

**Comment by Gutz-Pilz** [comment]
geht jetzt :+1: ?
49 01.02.2015 13:22:00 INFO HDaFetcher: COLLECTOR: Maze Runner - Die Auserwaehlten im Labyrinth (2014) IMDb: 6.9
50 01.02.2015 13:22:00 INFO Added package Maze Runner - Die Auserwaehlten im Labyrinth (2014) IMDb: 6.9 containing 1 links

**Comment by feuerwasser85** [comment]
in kurzfassung: 3 files hat er nun gefunden, allerdings nur sincity2, maze runner und amer.
laut einstellung (genau wie vorher) müsste er aber laut rss den großen gatsby gleich in die warteschlange geben, statt dessen wird er als "already fetched" markiert.

**Comment by Gutz-Pilz** [comment]
das ist echt komisch...
dann such ich dir mal die alte version raus

**Comment by Gutz-Pilz** [comment]
https://raw.githubusercontent.com/Gutz-Pilz/pyLoad-stuff/3a2d2c1f59a1ba8000cece6c8739a48298d22817/HDAreaOrg.py

**Comment by feuerwasser85** [comment]
danke! das ist aber doch auch die 1.1 oder?

**Comment by Gutz-Pilz** [comment]
ja...habe die versionsnummer nicht geändert ;)
aber die funktion "already fetched" ist nicht dabei

**Comment by feuerwasser85** [comment]
werd ich gleich ausprobieren, danke!

**Comment by feuerwasser85** [comment]
das andere plugin wird nicht mal aktiviert.

**Comment by feuerwasser85** [comment]
Nachdem ich jetzt wieder ein bisschen Zeit hatte, hab ich mich nochmal dran gemacht das Problem zu lösen aber ohne jeglichen Erfolg.
Bei mir wird grundsätzlich jeder Film als "already fetched" im debug markiert.
Mein Vorgehen:
1. Pyload mit start-script stoppen
2. files.db, files.db-journal, HDAreaOrg.py, HDAreaOrg.pyc, plugin.conf, pyload.conf löschen
3. HDAreaOrg.py neu erstellen mit C&P der RAW Codezeilen
4. Pyload starten

Sobald die getan ist, markiert er wieder alles mit "already fetched".
Wo werden die Daten noch gespeichert? Wie kann das sein?
Wäre super, wenn da jemand eine Idee hätte.

**Comment by Gutz-Pilz** [comment]
Kann ich mir nicht erklären.
Habe ja vor kurzem gerade auch des öfteren die files.db löschen müssen um die notification zu testen.
Da hat alles geklappt. 

Hast du schon versucht pyload neu zu installieren?

**Comment by feuerwasser85** [comment]
Ja, hat auch nichts gebracht. Mich wundert eben besonders dass das SJ.py Plugin tadellos funktioniert.

**Comment by Gutz-Pilz** [comment]
änder mal die funktion get_title folgender maßen
        def get_title(self,soup1):
            for all in soup1.findAll("div", {"class" : "topbox"}):
                for title in all.findAll("div", {"class" : "title"}):
                    self.filter(all, title.getText())

**Comment by feuerwasser85** [comment]
danke, ich versteh den code soweit, nur schreiben könnt ich ihn selbst nicht. das überlass ich den profis :-)
die änderung auf die version ohne fetched bewirkt leider lediglich, dass nichts mehr ins log geschrieben wird. aber dem problem komm ich somit näher. Der Fehler tritt also schon beim getText auf, ich weiß nur nicht was da genau gemacht wird, da hier ja nichts gespeichert wird. Meine Vermutung ist, dass er die Links einfach nur nicht übergibt, so laufen beide Versionen ins leere und die Version incl. fetched loggt es als already fetched.

**Comment by feuerwasser85** [comment]
Welche Python Version hast du bei Dir installiert? Könnte eventuell sein dass ihm eine lib fehlt zb. soup1 aus der BeautifulSoup?

**Comment by Gutz-Pilz** [comment]
ich hab python 2.7.3
soup1 ist nur ein variablenname

**Comment by feuerwasser85** [comment]
sorry, mein fehler
bei mir läuft python 3 mit dem python module und DSM 5.1-5022 Update 4 sowie das Pyload Paket von enkidu.

**Comment by Gutz-Pilz** [comment]
self.core.log.debug("Debugtext")

Füge die zeile mal an die stellen ein wo du denkst dass das script nicht weiter kommt.
Und poste dann mal bitte den log!

"Debugtext" darfst du gerne inividualisieren und nicht vergessen richtig einzurücken :)

**Comment by Gutz-Pilz** [comment]
gabs ein erfolg `?

**Comment by feuerwasser85** [comment]
hi. hab es jetzt ausgiebig getestet.
mein nun funktionierendes Ergebnis:
Habe Pyload nochmal neu installiert, diesmal mit dem Standardpfad als Configpfad (im Enkidu Paket das ich verwende standardmäßig /volume1/pyload) nun zu /volume1/@appstore/pyload/var/config.
Siehe da es funktioniert. Scheinbar verhält sich die files.db im Standardverzeichnis anders?!?
