### ISSUE TITLE
[SJ.py] Pushbullet Support

### ISSUE THREAD

**Issue by I-RiX-I** [Gutz-Pilz/pyLoad-stuff#18]
Apart from the already working Pushover support, why not add Pushbullet as well. API is quite straightforward.

**Comment by Gutz-Pilz** [comment]
https://github.com/zapp-brannigan/pyLoad-stuff/commit/37924701bb1324af68ed7ed6d86a34ffdf8dab4b

**Comment by Gutz-Pilz** [comment]
thanks to @zapp-brannigan
