### ISSUE TITLE
FileBot um Plex erweitern

### ISSUE THREAD

**Issue by namealwaysinuse** [Gutz-Pilz/pyLoad-stuff#24]
Hallo Gutz-Pilz,

ist es evtl. möglich, dass du deine FileBot.py um Plex erweiterst?
Sollte ja theoretisch fast eine Copy und Paste Aufgabe sein, jedoch hab ich davon keinerlei Ahnung.

--def xbmc=host Tell the given Kodi/XBMC instance to rescan it's library
--def plex=host[:token] Tell the given Plex instance to rescan it's library. Plex Home instances require an authentication token.

**Comment by Gutz-Pilz** [comment]
ist erweitert.
schau mal obs klappt - kanns leider nicht testen
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/86e8cfecf52bd09a755a75b5af733c9afc859eb8

**Comment by namealwaysinuse** [comment]
Ich teste es die Tage, danke :)

Von meinem iPhone gesendet
