### ISSUE TITLE
FileBot.py not compatible with new archive_extracted event.

### ISSUE THREAD

**Issue by vicegold** [Gutz-Pilz/pyLoad-stuff#25]
As statet at the Forum, the arguments for archive_extracted have been changed. FileBot.py still relies on the old version.

http://forum.pyload.org/viewtopic.php?f=12&t=4158#p17579

**Comment by Gutz-Pilz** [comment]
changed. 
can u pls test if it works. im in the office at the moment and cant :)
https://github.com/Gutz-Pilz/pyLoad-stuff/blob/4552aee56c467081165c49313eb6cb1521ef9dce/FileBot.py

**Comment by vicegold** [comment]
There was a syntax error in the plex refresh line, which i have fixed in a pull request, but with that fixed, the error just changed:

Error calling event handler archive_extracted: >, (PyFile 456: test.part1.rar@UploadedTo, ), archive_extracted() takes exactly 2 arguments (3 given)

**Comment by vicegold** [comment]
Sorry, had missed your latest commit. It seems fixed now!

**Comment by Gutz-Pilz** [comment]
https://github.com/Gutz-Pilz/pyLoad-stuff/blob/master/FileBot.py

^^added a new function.
kannst du das testen ?

**Comment by vicegold** [comment]
Funktioniert. config vorrübergehend auf false gesetzt, Filebot config angepasst -> Wurde wieder auf true gesetzt.

Allerdings zerhaut es mir beim FileBot Config speichern immer noch die series/movie destination. Wird immer abgeschnitten. Glaube aber dass das an pyLoad liegt.

**Comment by Gutz-Pilz** [comment]
könnte man über den selben code lösen. müsstest du dir genauso einfach
individuell anpassen...macht für die "masse" kein sinn.
bekommst du hin, oder ?

Am 23. März 2015 um 17:07 schrieb Laurids Düllmann <notifications@github.com

**Comment by Gutz-Pilz** [comment]
könntest du mir den lof mal zeigen. ob er dann auch das plugin "reloaded"
nicht das er die archive nach dem entpacken trotzdem nicht löscht weil er
das plugin nicht neu geladen hat...

Am 23. März 2015 um 17:13 schrieb Hannes Müller <hannes.mueller87@gmail.com>
:

**Comment by Gutz-Pilz** [comment]
könntest du mir den log mal zeigen. 
ob er dann auch danach das plugin "reloaded"
nicht das er die archive nach dem entpacken trotzdem nicht löscht weil er das plugin nicht neu geladen hat...

**Comment by vicegold** [comment]
Bekomm' ich hin, danke!

Gibt aber doch ein problem mit dem Configpfad, der ist ja in Zeile 82, hardgecodet, sprich du fragst gar nicht nach der gespeicherten variable. Da wirft's bei mir einen error, weil anderer Pfad zur Config:

23.03.2015 17:02:42	WARNING	Download failed: test.part1.rar | [Errno 2] No such file or directory: u'/root/.pyload/plugin.conf'

**Comment by Gutz-Pilz** [comment]
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/65361266df0eb3b541b9a73d84c93ca95fa7bbe9

^^fixed. Danke!
