### ISSUE TITLE
Filebot no module fileinput

### ISSUE THREAD

**Issue by GamesGamble** [Gutz-Pilz/pyLoad-stuff#28]
I have this error when using the latest filebot.py and latest pyload version.

![filebot](https://cloud.githubusercontent.com/assets/8069434/6893227/7a93a244-d6cb-11e4-9f12-bbf6547f7233.jpg)

Can you fix this pls?

**Comment by Gutz-Pilz** [comment]
du musst deinem python fileinput hinzufügen

**Comment by GamesGamble** [comment]
I´ve really searched the whole web and doesn´t find anything helpfull. I have installed Pyload on Windows and the script worked till 24,2014 then the serienjunkies rewriter doesn´t worked anymore fixed it in March and fixed Trakt, too. So this is and the trakt lookup (Flexget trakt lookup doesn´t work with the new trakt, yet.) is actually my problem. It seems the fileinput module is a standalone and is installed on my python, too. fileinput.py in Lib folder is present, too.

**Comment by Gutz-Pilz** [comment]
please us the latest version
https://raw.githubusercontent.com/Gutz-Pilz/pyLoad-stuff/master/FileBot.py

**Comment by GamesGamble** [comment]
The Error is gone but it hasn´t executed. In the console it says
183	21.04.2015 16:43:11	DEBUG	ExtractArchive: C:\Program Files (x86)\pyload_DE\dist\UnRAR.exe vb -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pserienjunkies.org -v media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part11.rar
184	21.04.2015 16:43:12	DEBUG	ExtractArchive: Would delete: media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part11.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part01.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part02.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part03.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part04.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part05.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part06.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part07.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part08.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part09.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part10.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part11.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part12.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part13.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part14.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part15.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part16.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part17.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part18.rar, media\DE_Incomplete\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part19.rar
185	21.04.2015 16:43:12	INFO	ExtractArchive: Deleting 20 files
186	21.04.2015 16:43:12	INFO	ExtractArchive: tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.part11.rar | Extracting finished
187	21.04.2015 16:43:12	DEBUG	ExtractArchive: Extracted files: [u'media\\DE_Incomplete\\..\\DE_Complete\\NCIS.S12E12.Die.Heimkehrer.German.DD51.Dubbed.DL.1080p.iTunesHD.AVC-TVS', u'media\\DE_Incomplete\\..\\DE_Complete\\NCIS.S12E12.Die.Heimkehrer.German.DD51.Dubbed.DL.1080p.iTunesHD.AVC-TVS\\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.nfo', u'media\\DE_Incomplete\\..\\DE_Complete\\NCIS.S12E12.Die.Heimkehrer.German.DD51.Dubbed.DL.1080p.iTunesHD.AVC-TVS\\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.mkv']
188	21.04.2015 16:43:12	DEBUG	ExtractArchive: New file media\DE_Incomplete\..\DE_Complete\NCIS.S12E12.Die.Heimkehrer.German.DD51.Dubbed.DL.1080p.iTunesHD.AVC-TVS does not exists
189	21.04.2015 16:43:12	DEBUG	ExtractArchive: New file media\DE_Incomplete\..\DE_Complete\NCIS.S12E12.Die.Heimkehrer.German.DD51.Dubbed.DL.1080p.iTunesHD.AVC-TVS\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.nfo does not exists
190	21.04.2015 16:43:12	DEBUG	ExtractArchive: New file media\DE_Incomplete\..\DE_Complete\NCIS.S12E12.Die.Heimkehrer.German.DD51.Dubbed.DL.1080p.iTunesHD.AVC-TVS\tvs-ncis-dd51-ded-dl-18p-ithd-avc-1212.mkv does not exists
191	21.04.2015 16:43:12	DEBUG	FileBot-Hook: MKV-Checkup (package_extracted)
192	21.04.2015 16:43:12	DEBUG	Hier sind noch Archive
all rar archives from the file got already deleted by ExtractedArchive. ExtractedArchive has seperate archive folders for unfinished and finished downloads. //DE_Incomplete = Archive files //DE_Complete mkv files when finished. Just to mention for bugsearching. Worked 24/2014 with the same configuration.

**Comment by Gutz-Pilz** [comment]
dann sind wohl noch archive/rar-pakete im ordner...
kannst du mal checken ob Extractarchive auch wirklich die rar-archive gelöscht hat ?

**Comment by GamesGamble** [comment]
ja die rar archive vom jeweiligen Paket wurden gelöscht. Sind halt noch rar archive von anderen Packeten im ordner.

**Comment by Gutz-Pilz** [comment]
aso. du musst für jedes paket ein eigenen ordner anlegen lassen.
unter Einstellungen ->Allgemein -> Create folder for each package: an!

**Comment by GamesGamble** [comment]
habe ich nun eingestellt. Gilt das erst bei neunen Paketen oder auch schon bei Paketen in der Warteschlange? Wenn auch bei Paketen in der Warteschlange funktioniert es nicht.

**Comment by Gutz-Pilz** [comment]
Nur bei neu hinzugefügten paketen.

Von meinem iPhone gesendet

**Comment by GamesGamble** [comment]
Irgendwie funktioniert das auch nicht. Liegt aber anscheinend an ExtractedArchive bzw. Pyload.
Da normale Pfadangaben in Pyload für Windows nicht funktionieren musste ich hardlinks setzen und ..\ angaben und mit der einstellung, dass er für jedes Paket nen Ordner machen soll landen die Video Dateien nun in EN_Incomplete/EN_Complete statt in ../EN_Complete alle einstellungen sind stimmen noch. Und Filebot findet dementsprechend keine Dateien fürn umbenennen.

**Comment by Gutz-Pilz** [comment]
boah. hört sich nach einem ziemlichen gefrickel an.
bei windows kann ich dir leider nicht helfen.
poste dein problem doch mal in den entsprechenden Filebot thread im pyloadforum

**Comment by GamesGamble** [comment]
Der Fehler wäre nun auch gefixxt. Nun gibt es aber wiederum nen anderen Bug mit deinem script ^^
Ich hab folgende Einstellungen

Pyload>Allgemein>Allgemein
Download Folder G:\media\EN_Incomplete
Create folder for each Package: an

Pyload>Plugins>ExtractArchive>
move to trash: aus
Repair broken Archives: an
Activated: an
Overwrite files: an
Run after all Downloads was proceed: aus
Extract Archives in Archies: an
Try to extract broken Archives: an
Extract files to folder: G:\media\EN_Complete
Test archive before extracting: an
Use password file: an
Create subfolder for each package: an
Extract with full paths: an
Delete Archive after extraction: an

Das Problem ist, dein script liefert den Pfad G:\media\EN_Incomplete obwohl die Datei aber nun in G:\media\EN_Complete ist. 

amc.log
Parameter: clean = y
Parameter: skipExtract = y
Parameter: excludeList = pyload-amc.txt
Parameter: reportError = y
Parameter: artwork = y
Parameter: subtitles = en
Parameter: movieFormat = G:/media/Movies/{n}/{fn}
Parameter: seriesFormat = G:/media/EN_Series/{n}/Season {s}/{s00e00} - {t}
Parameter: xbmc = locahost
Parameter: extras = n
Argument: G:\media\EN_Incomplete\Legaler-Sicherheitskopie-Ordner 
Using excludes: G:\media\pyload-amc.txt (162)
No files selected for processing
Failure (°_°)

Die Datei befindet sich aber in G:\media\EN_Complete\Legaler-Sicherheitskopie-Ordner

**Comment by Gutz-Pilz** [comment]
boah. nicht gerade in 5minuten gemacht.
ich mach das hallt immer in meiner freizeit.
falls ich also demnächst zeit finde bau ich das noch mit ein

**Comment by GamesGamble** [comment]
Okay hört sich gut an. Danke. Und kannst das mit dem falschen Ordner fixen?

**Comment by Gutz-Pilz** [comment]
so. ich hab so ne ahnung
ersetze 2 zeilen (zeile 86 und 102)
```
download_folder = self.config['general']['download_folder']
```
mit folgendem:
```
download_folder = self.core.api.getConfigValue("ExtractArchive", "destination", section='plugin')
```

**Comment by GamesGamble** [comment]
not working.

**Comment by Gutz-Pilz** [comment]
dann lass es doch einfach sein mit extra entpack ordner !?
bei mir is es leer gelassen weil ich ja sowieso für jedes paket ein ordner erstellt bekomme
