### ISSUE TITLE
Filebot wird vor dem Entpacken ausgeführt

### ISSUE THREAD

**Issue by GamesGamble** [Gutz-Pilz/pyLoad-stuff#34]
Pyload Log:
http://pastebin.com/4app3AAq
Filebot wird anscheinend vor dem Entpacken ausgeführt. Jedenfalls hat filebot seinen script nicht ausgeführt. Der Fehler ist seit mehreren Monaten schon vorhanden.

**Comment by Gutz-Pilz** [comment]
```
17.06.2015 01:43:42 DEBUG     FileBot: MKV-Checkup (packageFinished)
17.06.2015 01:43:42 DEBUG     FileBot: Hier sind noch Archive
```
^^gib mal bitte noch den log nach "package_extracted" mit an. (also `FileBot: MKV-Checkup (package_extracted)`)
vor dem entpacken geht nicht, weil noch archive im ordner sind.
Erst wenn "ExtractArchive" nach dem entpacken die Archive gelöscht hat wird filebot angeschmissen.

Beste Grüße

**Comment by Gutz-Pilz** [comment]
Habe den fehler gerade auch bei mir entdeckt.
Ich glaube ich kenn schon den fehler - in pyload selbst wurde an dem Eventhandling rumgeschraubt

**Comment by GamesGamble** [comment]
http://pastebin.com/hVuBRKSG

Das das einzige was dort noch steht :D

**Comment by Gutz-Pilz** [comment]
dann schau mal ob im ordner wirklich noch archive sind. wenn ja. dann ist das der grund warum filebot nicht läuft.
ansonsten kann man in den settings einstellen das sie gelöscht werden sollen.

**Comment by Gutz-Pilz** [comment]
sollte hiermit gefixed sein
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/96a0b440d1e87734b1613bdc3d36deb4eddf9adc

bitte neue version benutzen
https://raw.githubusercontent.com/Gutz-Pilz/pyLoad-stuff/master/FileBot.py
