### ISSUE TITLE
InvalidPathException: Illegal char

### ISSUE THREAD

**Issue by GamesGamble** [Gutz-Pilz/pyLoad-stuff#36]
http://pastebin.com/xiPyDXtS
Pyload Log

http://pastebin.com/prEkakAV
amc.log

Jetzt wird der Script zwar ausgeführt aber es kommt zu nem Fehler. Fakt ist im Ordner ist ne .mkv und .nfo datei keine Archive müsste also klappen. Im amc.log steht etwas das überhaupt keinen Sinn ergibt, da 1. Z:\Pyload\data\media\EN_Complete\ garnicht existiert und 2. das nix mit Z:\EN_Incomplete\Wikinger zu tun hat, wesßhalb das script ja ausgeführt wird.

EDIT: Der fehler tritt permanent auf. Also immer.

**Comment by Gutz-Pilz** [comment]
das liegt jetz wohl an filebot...
der hook gibt den richtigen pfad an filebot weiter. der hat aber vielleicht noch irgendwelchen alten karteileichen die er versucht zu lösen.

mal filebot neu installiert ?
die lock datei mal löschen ?

**Comment by GamesGamble** [comment]
It caused by the Filebot Hook says Rednoah.
"Yep. Looks like illegal paths are passed into FileBot so it's probably a FileBot Hook issues.

Looks like this is passed in as a single argument:
Code: Select all
C:\Program Files (x86)\Pyload_EN\data\media\EN_Complete\The.Flash.2014.S01E15.Out.of.Time.1080p.WEB-DL.DD5.1.H.264-NTb.mkvC:\Program Files (x86)\Pyload_EN\data\media\EN_Complete\Arrow.S03E02.Sara.1080p.WEB-DL.DD5.1.H.264-BS.mkv


Clearly that should be 1 argument per file. And there's something funky going on with relative paths being passed in as well. Can't pass relative paths unless you set filebot working dir correctly.
"

http://www.filebot.net/forums/viewtopic.php?f=4&t=2800&p=15774#p15774

**Comment by GamesGamble** [comment]
hmm. Filebot neuinstalliert habe ich. Was für ne Lock Datei?

**Comment by Gutz-Pilz** [comment]
ist es denn gelöst ?

**Comment by GamesGamble** [comment]
ja habe ich doch geschrieben :D 
Das löschen aller Einträge, wo der Ordner nicht mehr existiert in der exlcude List hat das Problem behoben. Ev. hätte auch nur der Eintrag wo die beiden URLs in einer Zeile waren gereicht.
