### ISSUE TITLE
WARNING	Konnte Filebot nicht aktivieren

### ISSUE THREAD

**Issue by acidburn78** [Gutz-Pilz/pyLoad-stuff#40]
Hello i have the Problem that Filebot.py isn't activated in Pyload 0.4.9 

what i did:
touch filebot.py
nano filebot.py
copy and paste the rawcode

but in the Log is always the error WARNING	Konnte Filebot nicht aktivieren

**Comment by Gutz-Pilz** [comment]
fixed
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/534b63f86758fde573e5ccd8a92d89eb14e7ef21

**Comment by acidburn78** [comment]
bekomme trotz update den fehler leider immer noch
