### ISSUE TITLE
ERROR	Error executing hooks: 'changeNameSJ'

### ISSUE THREAD

**Issue by acidburn78** [Gutz-Pilz/pyLoad-stuff#41]
ERROR	Error executing hooks: 'changeNameSJ'

den Fehler habe ich jetzt beim SJ.py hook

**Comment by Gutz-Pilz** [comment]
komisch. funktioniert bei mir.
du kannst entweder zeile 83 bis 85 löschen
oder ich packe meine Serienjunkies decrypter plugin hier irgendwo hoch. (an dem ich nie was geändert hab)

**Comment by acidburn78** [comment]
Fehler gefunden, seit der ganzen Update-Sache bei Pyload fehlte der SerienjunkiesOrg.py im crypter Ordner. Die hier eingefügt : http://forum.pyload.org/viewtopic.php?f=7&t=3680&start=40 und schon tritt der Fehler nicht mehr auf. Was noch bleibt ist das Captchas durch 9kw.eu scheinbar nicht gelöst werden...

**Comment by TheKas** [comment]
Ich hatte den Fehler auch die ganze Zeit und die hooks HDarea und SJ funktionierten nicht.
Ich habe danach eine alte Konfiguration von SerienjunkiesOrg in das plugin.conf kopiert und siehe da, nach einem Neustart funktionierte alles wieder wie gewünscht.

Das Problem ist, dass mit dem aktuellen SerienjunkiesOrg Plugin eine komplett andere Config geschrieben wird, mit der die Plugins nicht mehr funktionieren!

Ich verstehe zwar den Zusammenhang nicht ganz, aber es funktionierte bei mit mit folgender Konfiguration:
```
SerienjunkiesOrg - "SerienjunkiesOrg":
    str hosterList : "Preferred Hoster list (comma separated)" =
    bool randomPreferred : "Randomize Preferred-List" = False
    Only one;Only preferred (One);Only preferred (All);All hosterListMode : "Use for" = All
    Packagename;Show;Format;Episode changeNameDJ : "Take DJ.org name" = Packagename
    Packagename;Show;Season;Format;Episode changeNameSJ : "Take SJ.org name" = Packagename
    bool use_subfolder : "Save package to subfolder" = True
    str ignoreList : "Ignored Hoster list (comma separated)" =
    bool subfolder_per_package : "Create a subfolder for each package" = True 
```
