### ISSUE TITLE
Filebot kann immer noch nicht aktiviert werden

### ISSUE THREAD

**Issue by acidburn78** [Gutz-Pilz/pyLoad-stuff#42]
Vielleicht irgendwo noch nen schreibfehler drin? kenne mich da leider nicht so genau aus

**Comment by acidburn78** [comment]
zusätzlich bekomme ich noch folgende Fehlermeldung im LOG wenn ich eine Änderung im HOOK mache. Vielleicht hängt das ja zusammen und hilft bei der Fehlersuche

Error calling event handler pluginConfigChanged: >, ('Filebot', 'activated', True), 'module' object has no attribute 'Filebot'

**Comment by Gutz-Pilz** [comment]
verstehe ich nicht. bei mir läuft es super
is dein pyload auf dem aktuellsten stand ?

**Comment by acidburn78** [comment]
Ja ist die aktuelle stabile Version. Stimmt eventuell was mit den rechten
nicht? Läuft auf eine synology
Am 30.07.2015 17:53 schrieb "Gutz-Pilz" <notifications@github.com>:

**Comment by Gutz-Pilz** [comment]
momentan besteht das problem, dass ExtactArchive filebot nicht triggered.
liegt also am ExtractArchive hook das Filebot nicht richtig getriggered wird.

ODer was meinst du mit "lässt sich nicht aktivieren" ??

**Comment by acidburn78** [comment]
Nein es bedeutet wenn ich pyload starte bekomme ich die Meldung Error
könnte filebot nicht aktivieren. Und unter den aktivvierten plugins steht
es eben auch nicht
Am 30.07.2015 18:13 schrieb "Gutz-Pilz" <notifications@github.com>:

**Comment by Gutz-Pilz** [comment]
okay.
hast du die neueste version von meinem Github installiert ?

**Comment by acidburn78** [comment]
Wenn die Version von heute morgen die aktuelle ist dann ja ;)
Am 30.07.2015 18:31 schrieb "Gutz-Pilz" <notifications@github.com>:

**Comment by acidburn78** [comment]
Jetzt funktioniert es komischerweise, habe nochmal die py und die pyc gelöscht und die py neu angelegt. Nun kann es aktiviert werden. Frag mich bitte nicht warum! Versionsnummer war von der neuen Version
