### ISSUE TITLE
SJ.py sucht jede Minute nach neuen Episoden

### ISSUE THREAD

**Issue by DKeppi** [Gutz-Pilz/pyLoad-stuff#43]
Hallo,

habe das Interval wie bisher auch auf 60 (Minuten) eingestellt.
Trotzdem sucht das SJ.py jede Minute nach neuen Episoden lt. SJ.txt
Habe bereits versucht pyLoad neu zu starten, das SJ.pyc File zu löschen und dergleichen, leider ohne Erfolg - irgend eine Idee?

1	30.07.2015 13:30:40	INFO	pyLoad is up and running
2	30.07.2015 13:30:40	INFO	HOOK UpdateManager : No new pyLoad version available
3	30.07.2015 13:30:40	DEBUG	HOOK UpdateManager : Requested deletion of plugins: [(u'accounts', u'BillionuploadsCom'),....
4	30.07.2015 13:30:40	INFO	HOOK UpdateManager : No plugin updates available
5	30.07.2015 13:30:50	INFO	HOOK ClickAndLoad : Proxy listening on 0.0.0.0:9666
6	30.07.2015 13:31:02	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E06.720p.HDTV.x264-0SEC
7	30.07.2015 13:31:02	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E06.HDTV.x264-KILLERS
8	30.07.2015 13:31:03	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E05.720p.HDTV.x264-0SEC
9	30.07.2015 13:31:03	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E05.INTERNAL.HDTV.x264-BATV
10	30.07.2015 13:31:03	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E04.720p.HDTV.x264-0SEC
11	30.07.2015 13:31:03	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E04.INTERNAL.HDTV.x264-BATV
12	30.07.2015 13:32:16	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E06.720p.HDTV.x264-0SEC
13	30.07.2015 13:32:16	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E06.HDTV.x264-KILLERS
14	30.07.2015 13:32:16	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E05.720p.HDTV.x264-0SEC
15	30.07.2015 13:32:16	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E05.INTERNAL.HDTV.x264-BATV
16	30.07.2015 13:32:16	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E04.720p.HDTV.x264-0SEC
17	30.07.2015 13:32:16	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E04.INTERNAL.HDTV.x264-BATV
18	30.07.2015 13:33:29	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E06.720p.HDTV.x264-0SEC
19	30.07.2015 13:33:29	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E06.HDTV.x264-KILLERS
20	30.07.2015 13:33:29	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E05.720p.HDTV.x264-0SEC
21	30.07.2015 13:33:29	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E05.INTERNAL.HDTV.x264-BATV
22	30.07.2015 13:33:29	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E04.720p.HDTV.x264-0SEC
23	30.07.2015 13:33:29	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E04.INTERNAL.HDTV.x264-BATV
24	30.07.2015 13:34:42	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E06.720p.HDTV.x264-0SEC
25	30.07.2015 13:34:42	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E06.HDTV.x264-KILLERS
26	30.07.2015 13:34:42	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E05.720p.HDTV.x264-0SEC
27	30.07.2015 13:34:42	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E05.INTERNAL.HDTV.x264-BATV
28	30.07.2015 13:34:42	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E04.720p.HDTV.x264-0SEC
29	30.07.2015 13:34:42	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E04.INTERNAL.HDTV.x264-BATV
30	30.07.2015 13:35:55	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E06.720p.HDTV.x264-0SEC
31	30.07.2015 13:35:55	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E06.HDTV.x264-KILLERS
32	30.07.2015 13:35:55	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E05.720p.HDTV.x264-0SEC
33	30.07.2015 13:35:55	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E05.INTERNAL.HDTV.x264-BATV
34	30.07.2015 13:35:55	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E04.720p.HDTV.x264-0SEC
35	30.07.2015 13:35:55	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E04.INTERNAL.HDTV.x264-BATV
36	30.07.2015 13:37:08	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E06.720p.HDTV.x264-0SEC
37	30.07.2015 13:37:08	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E06.HDTV.x264-KILLERS
38	30.07.2015 13:37:08	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E05.720p.HDTV.x264-0SEC
39	30.07.2015 13:37:08	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E05.INTERNAL.HDTV.x264-BATV
40	30.07.2015 13:37:08	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E04.720p.HDTV.x264-0SEC
41	30.07.2015 13:37:08	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E04.INTERNAL.HDTV.x264-BATV
42	30.07.2015 13:38:21	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E06.720p.HDTV.x264-0SEC
43	30.07.2015 13:38:21	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E06.HDTV.x264-KILLERS
44	30.07.2015 13:38:21	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E05.720p.HDTV.x264-0SEC
45	30.07.2015 13:38:21	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E05.INTERNAL.HDTV.x264-BATV
46	30.07.2015 13:38:21	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E04.720p.HDTV.x264-0SEC
47	30.07.2015 13:38:21	DEBUG	HOOK SJ : Abgelehnt: [ENGLISCH] True.Detective.S02E04.INTERNAL.HDTV.x264-BATV

**Comment by Gutz-Pilz** [comment]
ich weiß versuch das problem gerade zu lösen

**Comment by Gutz-Pilz** [comment]
fixed
