### ISSUE TITLE
Filebot macht nix 

### ISSUE THREAD

**Issue by must4rd** [Gutz-Pilz/pyLoad-stuff#44]
Hey ich hoffe du kannst mir helfen. 
Hab eine ds214play und pyload 0.4.9 und die aktuelle filebot.py im hook ordner. 
hook wird auch geladen, aber nach dem entpacken nicht ausgeführt.
bin seit knapp 24 stunden da dran und finde den fehler nicht...
reicht es beim filebot executeable nur "filebot" rienzuschreiben, oder muss da "/volume1/@appstore/filebot/filebot.sh" rein?
Ich finde die Funktion echt super und würd mich freuen wenn du mir helfen kannst.
Und danke für die Arbeit!
mfg must4rd

**Comment by Gutz-Pilz** [comment]
ich geh davon aus, dass du es auf einem Synology benutzt ?
dann brauchst du unter executable nichts reinschreiben.

momentan funktioniert der hook nur wenn du direkt eine MKV lädst.
die events werden momentan nicht richtig getriggert und dadurch wird nach erfolgreichen entpacken das filebot hook nicht angesprochen.

ich warte auf feedback und fix von den pyload devs. sorry

**Comment by Gutz-Pilz** [comment]
okay. geht wieder.
bitte die aktuellste FileBot.py laden

https://raw.githubusercontent.com/Gutz-Pilz/pyLoad-stuff/master/FileBot.py

**Comment by must4rd** [comment]
haha nice...hatte gestern abend immer wieder nur avi´s ausprobiert...jetzt läufts anscheinend...
eine Hilfe bräuchte ich noch...hatte das zwar iwo im forum gefunden, aber jetzt net mehr....
was schreib ich in destination rein, damit ich zum Beispiel folgendes Verzeichnis hab:
/volume1/video/Movie/Avatar (2009)/Avatar(2009).mkv
und für Serien
/volume1/video/TV Shows/Dexter/Season 1/Dexter - S01E01 - titel.mkv
Dann wäre alles perfekt xD
Danke dir!
mfg must4rd

**Comment by Gutz-Pilz** [comment]
für Serien
```
/volume1/video/TV Shows/{n}/Season {s.pad(2)}/{n} - {s00e00} - {t}
```

für Filme
```
/volume1/video/Movie/Movies/{n} ({y})/{n} ({y})
```

**Comment by must4rd** [comment]
Du bist der beste! Danke
