### ISSUE TITLE
[Feature Request] Anfrage: Update der Hooks mit Updatemanager?

### ISSUE THREAD

**Issue by acidburn78** [Gutz-Pilz/pyLoad-stuff#45]
Hallo Gutz-Pliz,

ist es eigentlich möglich deine Hooks mit dem Updatemanager von Pyload aktuell zu halten?? Oder gibt es da eine andere Möglichkeit?

Gruß

**Comment by Gutz-Pilz** [comment]
Hi, 

über den Updatemanager wird es wohl nicht möglich sein, da meine Hooks nicht offiziell im pyload rep mitgeführt werden.
Kann ich für SJ und HDarea verstehen.
Bei FileBot scheitert es, weil es ein filebot als extraprogramm vorraussetzt.

ich mach mich mal schlau ob sowas generell möglich ist.

Danke

**Comment by no-Legend** [comment]
Ich könnte mir zwei Methoden vorstellen.

1. Du könntest in deinem Script eine einfache Versionkontrolle einführen mit Benachrichtigung der User per Email, Pushober oder des gleichen.
2. Könnte man nicht einfach einen git clone machen?
Also in den Hooks?
Dann würde man einfach einen pull machen und hat immer wieder die Aktuellste Version.



Gruß Robert

**Comment by Gutz-Pilz** [comment]
zu 1.
Schwierig - da jeder eine email oder Push* angeben muss.

zu 2.  recherchiere ich :)

**Comment by Gutz-Pilz** [comment]
http://stackoverflow.com/questions/31918875/self-updating-python-scripts?answertab=active#tab-top

^^ich hab mal auf stackoverflow gefragt.
der letzt comment ist gut. 

daraufhin habe ich entschieden es nicht in den code zu schreiben um die sache nicht kompliziert zu machen. vorallem weil nicht jeder pyload als root laufen hat.

ich denke ich werde ein bash script für externalscripts schreiben

**Comment by Gutz-Pilz** [comment]
https://gist.github.com/Gutz-Pilz/ab988f48c912e66cb930

^^dieses script als externalscript in den ornder "pyload_start" packen
Zeile 5,7,8 und 9 anpassen
dann noch mit ordentlichen rechten versehen (chmod +x) und pyload neu starten

**Comment by Gutz-Pilz** [comment]
funktioniert das für euch ?

**Comment by acidburn78** [comment]
Habe ich noch nicht probiert. Kann ich erst am Montag sagen dann habe ich
zeit
Am 16.08.2015 11:55 schrieb "Gutz-Pilz" <notifications@github.com>:

**Comment by b2un0** [comment]
Funktioniert bei mir ohne Probleme :+1:  danke dafür!

**Comment by Gutz-Pilz** [comment]
@b2un0 
kennst du dich mit html, css usw aus ?
würde gerne ein standalone für HD-are und Serienjunkies á la directdownload.tv machen.

Im Prinzip ein RSS Generator mit schöner Weboberfläche.
Und so, dass es mit minimalem Aufwand für den User installierbar ist.

Die neue SJ-RSS.py in meinem Github-repo erstellt schonmal eine xml die evtl dann von HTML/PHP oder so ausgelesen werden könnte.

**Comment by acidburn78** [comment]
Bei mir scheint es noch nicht zu funktionieren.

Arbeite mit einer Synology bekomme beim start von pyload folgende Meldung:
DEBUG	Redirected import module.plugins.hooks.ExternalScripts -> userplugins.hooks.ExternalScripts
13	17.08.2015 12:37:52	DEBUG	HOOK ExternalScripts: Deprecated method `event_list`, use `event_map` instead

ich gehe aber mal davon aus das das mit dem ausführen nichts zu tun hat.

Ausserdem habe ich zwei scripts ordner einmal unter /volume2/@appstore/pyload/pyload und unter /volume2/@appstore/pyload/var/config
welchen der beiden muss ich nehmen und unter welchen user/root muss das script auseführt werden? bekomme keine Meldung im Log von pyload

**Comment by b2un0** [comment]
In dem Script fehlt noch eine Abfrage vor den "grep" Abfragen ob die Parameter gesetzt sind, ich bekommen bspw. folgende Meldung weil ich das HDAreaOrg Plugin nicht verwende.

```grep: /root/.pyload/userplugins/hooks/HDAreaOrg.py: No such file or directory```

**Comment by b2un0** [comment]
@Gutz-Pilz ja, ich kenne mich damit aus, bin Beruflich PHP-Entwickler.

**Comment by Gutz-Pilz** [comment]
Habs gefixt. danke für den Hinweis

@b2un0 
und was hältst du von dieser Idee ?

**Comment by b2un0** [comment]
Das gist script könntest du evtl komplet ohne konfiguration laufen lassen;

pyload fürt das script ja mit dem eigenen user aus, daher müsste gar nicht "pyLoadFolder" definiert werden sondern - untern Linux - lediglich ```~``` verwendet werden.

Außerdem könnte der Updater einfach in dem Ordner schauen ob die jeweiligen Dateien existieren, wenn ja, update sie, wenn nein, skippen;

also statt  ```if [ $HDAreaOrg = 1 ];then``` einfach  ```if [ -f "$hooks_folder/HDAreaOrg.py" ]; then```

Dann kann man das Script einfach per copy/paste in den *pyload_start* Ordner packen, ```chmod +x``` und fertig

**Comment by b2un0** [comment]
@Gutz-Pilz Erklär mir bitte nochmal die Idee genauer per E-Mail und häng ggf deinen Skype Namen mit ran, das dürfte es einfacher machen :+1:

**Comment by Gutz-Pilz** [comment]
gute idee - wird umgesetzt ;)
werd' mich die Tage mal bei dir melden

**Comment by b2un0** [comment]
werden ExternalScripts im *pyload_start* folder eigentlich auch bei *pyload_restart* ausgeführt?
Ansonsten leg ich einen symlink in *pyload_restart* an :)

**Comment by acidburn78** [comment]
bei mir kommt auch nix im LOG von pyload scheinbar macht ERxternalScripts noch Probleme?!?

**Comment by Gutz-Pilz** [comment]
hast du es im debug laufen ?

**Comment by acidburn78** [comment]
Ja ich habe es im Debug laufen, es wird scheinbar nichts ausgeführt

**Comment by Gutz-Pilz** [comment]
@acidburn78 
ich geh davon, dass du ExternalScripts plugin aktiviert hast ?

https://gist.github.com/Gutz-Pilz/ab988f48c912e66cb930
^^voll automatisiert
@b2un0 
1. ich hab keine ahnung ob start auch bei restart ausgeführt wird :)
2. ich frag im script nach der eigenen Script location und cutte dann die letzten beiden slashs (sprich "/scripts/*" - scheint mir sicherer :)

**Comment by b2un0** [comment]
Die neue Version funktioniert vom Terminal wunderbar, mal schauen ob es auch mit pyLoad geht.

** ExternalScripts** ist bei mir jedenfalls aktiviert.

**Comment by acidburn78** [comment]
ExternalScripts ist bei mir auch aktiviert aber es läuft nicht.....

**Comment by Gutz-Pilz** [comment]
vielleicht bekommst du es nur nicht mit.
hab gesehen das ich es im WEBui dort im log auch nicht zu gesicht bekomme.
hab mal ne neue version gemacht - diese schreibt jetzt in die Log.

https://gist.github.com/Gutz-Pilz/ab988f48c912e66cb930

^^bitte mal testen

**Comment by acidburn78** [comment]
in der WEBui bekomme ich immer noch nix zu sehen.

@b2un0 wie und mit welchen optionen startest du das script den vom Terminal? Ich will mal schauen ob es da für mich auch funktioniert

wenn ich es im Terminal starte mit ./pyLoadStuff_updater.sh bekomme ich keine Meldung, wenn ich es mit sh pyLoadStuff_updater.sh starte bekomme ich folgende Meldung:
config/scripts/pyload_start> sh pyLoadStuff_updater.sh
pyLoadStuff_updater.sh: line 3: function: not found
pyLoadStuff_updater.sh: line 13: bc: not found
pyLoadStuff_updater.sh: line 13: logit: not found
pyLoadStuff_updater.sh: line 13: logit: not found
rm: can't remove 'SJ.p*': No such file or directory
pyLoadStuff_updater.sh: line 13: logit: not found
pyLoadStuff_updater.sh: line 14: syntax error: unexpected "}"

**Comment by DKeppi** [comment]
ExternalScripts.py ist schon länger nicht funktionsfähig, deshalb läuft es bei keinem.
Ich habe einfach das ExternalScripts.py vom pullrequest https://github.com/pyload/pyload/pull/1728/files in den userpluginsordner gelegt, dann gehts


Bekomme aber auch einen Fehler!

INFO	HOOK ExternalScripts: Registered script: [pyload_start] scripts/pyload_start/Gutz-Pilz_hooks-updater.sh
INFO	HOOK ExternalScripts: Installed scripts in folder `pyload_start`: scripts/pyload_start/Gutz-Pilz_hooks-updater.sh
INFO	HOOK ExternalScripts: Installed scripts in folder `all_archives_extracted`: scripts/all_archives_extracted/filebot.sh
INFO	HOOK ExternalScripts: EXECUTE [/volume1/pyload/scripts/pyload_start] ['/volume1/pyload/scripts/pyload_start/Gutz-Pilz_hooks-updater.sh']
ERROR	HOOK ExternalScripts: Runtime error: /volume1/pyload/scripts/pyload_start/Gutz-Pilz_hooks-updater.sh | [Errno 2] No such file or directory
DEBUG	HOOK ExternalScripts: Deprecated method `event_list`, use `event_map` instead

**Comment by acidburn78** [comment]
Bei mir wird es nun ausgeführt mit dem neuen ExternalScripts
Bekomme ebenfalls noch Fehlermeldungen:

132	18.08.2015 10:02:06	INFO	HOOK ExternalScripts: Registered script: [pyload_start] scripts/pyload_start/pyLoadStuff_updater.sh
133	18.08.2015 10:02:06	WARNING	HOOK ExternalScripts: Script not executable: [pyload_start] scripts/pyload_start/SJ.py
134	18.08.2015 10:02:06	INFO	HOOK ExternalScripts: Registered script: [pyload_start] scripts/pyload_start/SJ.py
135	18.08.2015 10:02:06	INFO	HOOK ExternalScripts: Registered script: [pyload_restart] scripts/pyload_restart/pyLoadStuff_updater.sh
136	18.08.2015 10:02:06	INFO	HOOK ExternalScripts: Installed scripts in folder `pyload_restart`: scripts/pyload_restart/pyLoadStuff_updater.sh
137	18.08.2015 10:02:06	INFO	HOOK ExternalScripts: Installed scripts in folder `pyload_start`: scripts/pyload_start/pyLoadStuff_updater.sh, scripts/pyload_start/SJ.py
138	18.08.2015 10:02:06	INFO	HOOK ExternalScripts: EXECUTE [/volume2/@appstore/pyload/var/config/scripts/pyload_start] ['/volume2/@appstore/pyload/var/config/scripts/pyload_start/pyLoadStuff_updater.sh']
139	18.08.2015 10:02:06	ERROR	HOOK ExternalScripts: Runtime error: /volume2/@appstore/pyload/var/config/scripts/pyload_start/pyLoadStuff_updater.sh | [Errno 2] No such file or directory
140	18.08.2015 10:02:06	INFO	HOOK ExternalScripts: EXECUTE [/volume2/@appstore/pyload/var/config/scripts/pyload_start] ['/volume2/@appstore/pyload/var/config/scripts/pyload_start/SJ.py']
141	18.08.2015 10:02:06	ERROR	HOOK ExternalScripts: Runtime error: /volume2/@appstore/pyload/var/config/scripts/pyload_start/SJ.py | [Errno 13] Permission denied
142	18.08.2015 10:02:06	DEBUG	HOOK ExternalScripts: Deprecated method `event_list`, use `event_map` instead

**Comment by Gutz-Pilz** [comment]
sdo. es gab ne zeit lang ein falschen Updatemanager.py
löscht mal die letzte updatemanager.py in den hooks ordner
```
cd /root/.pyload/userplugins/hooks/
rm UpdateManager.py
wget https://raw.githubusercontent.com/pyload/pyload/6f5062a7ac02c8d583c7f9d480be69e3ee83c05c/module/plugins/hooks/UpdateManager.py
```
pyload neustarten. dann dürfte der Updater wieder funktionieren und pyload müsste die letzte und funktionierende Externalscript.py ziehen


@DKeppi 
./updater.sh ist richtig
^^wenn das script in "pyload_start" liegt dürfte nach ausführen was im pyload-log stehen

**Comment by DKeppi** [comment]
@Gutz-Pilz

Das Script liegt in pyload_start aber es kommt der Fehler
ERROR	HOOK ExternalScripts: Runtime error: /volume1/pyload/scripts/pyload_start/Gutz-Pilz_hooks-updater.sh | [Errno 2] No such file or directory

Verwendest du es auch auf einer Synology?
Bash gibts da ja eigentlich keine, deswegen habe ich es mal auf #!/bin/sh geändert und der Fehler ist weg. Ob es funktioniert kann ich nicht sagen...function, logit etc. gibts auf der Syno eigentlich auch nicht!

**Comment by Gutz-Pilz** [comment]
Nein. Benutze es auf meinem 24/7 Debian Downloader (BananaPi)
In normaler shell müsste ich es umschreiben. Kenne ich mich nicht mit aus. Und keine Ahnung ob das funktioniert.

 Es ist sehr schwierig eine Diagnose zu machen was jetzt wie und wann die SJ.py in root erzeugt hat.
Kannst du sie mal löschen und bei jedem ausführen des Updaters root auflisten um nachzusehen welcher befehl genau diese SJ.py erzeugt hat ?

Greifst du mit SSH zu und hast eine direkte Ausgabe auf dem Screen ?

**Comment by DKeppi** [comment]
Ok, dann wäre es für Syno-Nutzer nur etwas mit ipkg - da kann man bash nachinstallieren.

Greife per SSH über putty zu, allerdings kommt da eben nur
line 3: function: not found
usw.

Sehe also leider auch nicht woher die genau kommt, sorry!

**Comment by Gutz-Pilz** [comment]
okay. schade. vielleicht kannst du ja mal bei stackoverflow nachfragen ob man das script umschreiben kann

**Comment by acidburn78** [comment]
würde mich dann auch interessieren nutze ebenfalls eine Synology

**Comment by DKeppi** [comment]
Machen die denn sowas?
Kenne die Seite gar nicht ;)

Viell. kannst du ja auch ein Hook draus machen, das läuft dann überall.
Evtl. mit Auswahl, welche deiner Scripte man verwendet...

**Comment by Gutz-Pilz** [comment]
habe ich auch schon drüber nachgedacht.
Muss ich schauen ob das so einfach ist. Habe ich momentan aber eigtl keine
Zeit dafür.
Vielleicht erbarmt sich @b2uno ;)

Am 19. August 2015 um 07:05 schrieb DKeppi <notifications@github.com>:

**Comment by DKeppi** [comment]
:) Wer hat schon Zeit :)
Aber es eilt ja nicht...
