### ISSUE TITLE
Funktionen hinzufügen

### ISSUE THREAD

**Issue by no-Legend** [Gutz-Pilz/pyLoad-stuff#46]
Hallo Lutz-pilz,

kannst du meinen Änderungen am pushover einpflegen oder kann ich das selber?
Habe nicht so die Erfahrung mit Git.

Gruß Robert

**Comment by Gutz-Pilz** [comment]
einfach ein pullrequest erstellen
einfach in meinem git auf die gewünschte datei und dann oben rechts auf den stift.
dort dann deine änderungen einfügen und speichern.
danach kannst due ein request erstellen
https://help.github.com/articles/using-pull-requests/

ansonsten kannst du mir den code auch hier in die comments schreiben.
aber bitte markdown benutzen.

danke

**Comment by no-Legend** [comment]
Schau mal ob ich alles richtig gemacht habe.
Hab mal ein Pull request gemacht

**Comment by Gutz-Pilz** [comment]
schon passiert.
danke nochmal.

**Comment by no-Legend** [comment]
Kein ding.
Für mein erstes bissel wieder im programmieren seit Jahren.
Dazu noch eine sprache die ich eigentlich gar nicht kenne.

Dazu danke ich dir!
Dein Hooks ist einer der Gründe warum ich nach dem Update Debakel bei pyload nicht gleich wieder bei JDownload gelandet bin!
