### ISSUE TITLE
SJ.py x264 ABGELEHNT

### ISSUE THREAD

**Issue by DKeppi** [Gutz-Pilz/pyLoad-stuff#48]
Hallo Gutz-Pilz,

bei mir wird beim aktuellen SJ.py trotz Einstellung 480p die neueste Simpsons Folge abgelehnt

19.08.2015 07:11:18	DEBUG	HOOK SJ: Abgelehnt: [DEUTSCH] Die.Simpsons.S26E01.Ein.trauriger.Clown.GERMAN.DUBBED.720p.HDTV.x264-ZZGtv
308	19.08.2015 07:11:18	DEBUG	HOOK SJ: Abgelehnt: [DEUTSCH] Die.Simpsons.S26E01.Ein.trauriger.Clown.GERMAN.DUBBED.DL.1080p.WebHD.x264-TVP
309	19.08.2015 07:11:18	DEBUG	HOOK SJ: Abgelehnt: [DEUTSCH] Die.Simpsons.S26E01.Ein.trauriger.Clown.German.Dubbed.HDTV.x264-ITG

Die ersten beiden passen, das sind ja 1080p und 720p, aber das dritte wäre die 480p Version!

![19-08-2015 07-15-50](https://cloud.githubusercontent.com/assets/2063381/9349176/2d573af4-4642-11e5-9b44-35321401b177.jpg)

Oder mache ich etwas falsch?

**Comment by Gutz-Pilz** [comment]
aso... lädst du generell 480p herunter. bei allen serien ?
wie seht deine SJ.txt aus ?

Am 19. August 2015 um 07:16 schrieb DKeppi <notifications@github.com>:

**Comment by DKeppi** [comment]
Ja genau, lade nur 480p

Meine SJ.txt ist simpel und ohne Angabe von Sprache oder Qualität
z.B. steht da nur

Die Simpsons
The Walking Dead
usw.

**Comment by Gutz-Pilz** [comment]
dann musst du "einträge aus der suchdatei" auf aus stellen

2015-08-19 8:38 GMT+02:00 DKeppi <notifications@github.com>:

**Comment by DKeppi** [comment]
Habs umgestellt, jetzt findet er die 1080 & 720er Versionen nicht mehr bzw. listet sie im DEBUg Modus nicht mehr auf - passt!

Allerdings lehnt er die x264er Version wieder ab :(
Kann es sein das es an dem HDTV im Namen liegt?

**Comment by DKeppi** [comment]
Jetzt gibt es ein zweites in 480p, wird aber auch abgelehnt :(

DEBUG	HOOK SJ: Abgelehnt: [DEUTSCH] Die.Simpsons.S26E01.Ein.trauriger.Clown.German.DL.DD51.Dubbed.WEBRip.x264-GDR

Hast du eine Idee an was das liegen kann?

**Comment by Gutz-Pilz** [comment]
dürfte so jetzt funktionieren :)

**Comment by DKeppi** [comment]
Danke, werd mich melden sobald ich ein paar Tage getestet habe :)

**Comment by DKeppi** [comment]
Heute zwei neue Episoden von verschiedenen Serien erfolgreich erkannt - DANKE!

**Comment by Gutz-Pilz** [comment]
sehr gut!
hannesmueller.com/donate.html
:)
