### ISSUE TITLE
Filebot.py self.log_Info

### ISSUE THREAD

**Issue by evilmon** [Gutz-Pilz/pyLoad-stuff#49]
Hi,

beim Ausführen von Filebot.py kommt es im Pyload zum Error: 
'FileBot' object has no attribute 'logInfo'

Du schreibst im Script an 2 Stellen "self.logInfo..." anstelle von "self.log_info..."

**Comment by evilmon** [comment]
Zeile 240 & 242

**Comment by Gutz-Pilz** [comment]
jaja. ist mir auch schon aufgefallen.
kein schwerwiegender fehler ;)

**Comment by Gutz-Pilz** [comment]
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/a5ee2659bdb8ca98efd65c1f681f2f2fd6623ab5#diff-3ac36d2493145772b7cc2f037bf7a27f

**Comment by b2un0** [comment]
@Gutz-Pilz ich denke da fehlt was im commit, das ist nur n version bump :)

**Comment by Gutz-Pilz** [comment]
das commit davor hats gefixed ;)

**Comment by Gutz-Pilz** [comment]
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/844c642f7d20a29698681a5f952dad71f8749226#diff-3ac36d2493145772b7cc2f037bf7a27f
