### ISSUE TITLE
HDAreaOrg - Hook - ShareonlineBiz

### ISSUE THREAD

**Issue by macross5** [Gutz-Pilz/pyLoad-stuff#50]
Hi! Danke erstmal für deine Hooks! Nachdem Flexget nicht mehr bei mir laufen möchte, bin ich auf deine Hooks umgestiegen und die laufen perfekt!

Zum Problem: 
Als bevorzugte Hoster habe ich eingestellt: uploaded;UploadedTo;UploadedNet
Dennoch wird zusätzlich zum Uploaded noch ShareonlineBiz eingefügt, sodass ich die Parts doppelt habe. Möchte aber nur durch Uploaded laden.

Grüße und vielen Dank.

**Comment by Gutz-Pilz** [comment]
Das ist ganz normal.
Auf hdarea gibt es sowieso (seit nem halben jahr oder so) nur noch ein link.
Ein link für beide hoster.
Ich nutze das plugin justpremium.
Ist mittlerweile teil von pyload und filtert nicht gewollte hosterlinks raus.

**Comment by b2un0** [comment]
Danke für den Tip mit justpremium :+1:   :+1:

**Comment by macross5** [comment]
Vielen Dank. Damit funktioniert es nun perfekt!
