### ISSUE TITLE
SJ: No module named Hook 

### ISSUE THREAD

**Issue by WtfJoke** [Gutz-Pilz/pyLoad-stuff#51]
Ich hab den Hook in den Ordner pyload/module/plugins/hooks kopiert.
Danach habe ich den Hook in den pyload-Einstellungen konfiguriert. Im log steht aber jeweils nur:

```54	18.09.2015 22:23:08	ERROR	Fehler beim importieren von SJ: No module named Hook ```

Kennst du das Problem?

**Comment by Gutz-Pilz** [comment]
das sit komisch.
pyload ist auch aktuell ?

**Comment by WtfJoke** [comment]
Ja pyload ist aktuell. Ist ja nach wie vor 0.4.9 aktuell....

Ich muss dazu noch erwähnen, dass ich pyload auf dem NAS (Synlogy DS213) installiert habe. Allerdings hatte ich bisher keine Probleme mit Plugins, auch nicht mit 3rd Party Plugins wie diesem hier. :)

**Comment by must4rd** [comment]
Welche python version? SJ Hook funktioniert nur ab 2.6

**Comment by WtfJoke** [comment]
Die neuste 2er python version --> 2.7.10

**Comment by must4rd** [comment]
und pyload nutzt auch die version? nachgucken kannst du das unter der UI von pyload unter info oben rechts...
ich hatte den fehler weil pyload immer auf 2.5 gezeigt hat...

**Comment by WtfJoke** [comment]
Tatsächlich... Aus irgendeinem Grund verwendet pyload 2.7.2. :dizzy_face:
Weisst du noch wie du das umgebogen hast?

**Comment by must4rd** [comment]
2.7.2 sollte in ordnung sein...meine läuft mit 2.7.3..aber das sollte nicht das problem sein...2.6 sollte eigentlcih reichen. als ich den fehler hatte lief pyload unter 2.5 und der support von json etc kam leider erst mit 2.6.
Unter www.must4rd.de/UpdateManager findest du meinen update manager...ersetze den durch deinen und lass Pyload neustarten.
Wenn du das über paket manager installiert hast ist der Pfad:
/volume1/@appstore/pyload/var/config/userplugins/hooks/
Ich selber hab ne DS214Play aber mein "chef" hat meine alte ds213j und ich hab es da auch komplett alles zu laufen gebracht...also meld ich xD
reinhauen mfg must4rd

**Comment by WtfJoke** [comment]
ok... Danke für deine Hilfe. Nach dem ersetzen bekomme ich jetzt zusätzlich: 
Fehler beim importieren von UpdateManager: No module named Addon

**Comment by Gutz-Pilz** [comment]
ojee. du hastt eine alte pyload version. 
nun ist es eindeutig ;)

**Comment by WtfJoke** [comment]
Ich hab so etwas vermutet.... Aber ich versteh nicht warum es mir dann 0.4.9 als pyload-Verison anzeigt?

**Comment by b2un0** [comment]
Weil pyLoad die Version immer beibehält aber trotzdem die Dateien über den UpdateManager aktuallisiert.

wo liegt dein pyLoad?

unter /usr/share/pyload ?

dann wäre das einfach, ich musste den vorgestern auch manuell updaten.

**Comment by WtfJoke** [comment]
Ok. Ne liegt unter /volume1/@appstore/pyload/pyload (weil ich die pyload über diese Paketquelle http://spk.unzureichende.info/ installiert habe)

Kann ich den Ordner einfach ersetzen mit der neusten Pyload-Version? Wo würden die Einstellungen liegen, damit ich die zuerst sichern kann (Pyload-Einstellungen, Accounts etc..)

**Comment by b2un0** [comment]
deine Einstellungen liegen alle in ```/root/.pyload/*```
bzw unter dem user mit welchem pyLoad ausgeführt wird, z.B. ```/home/USER/.pyload/*```

Ich hab bei mir ```/user/share/pyload``` einfach mittels

```git clone https://github.com/pyload/pyload.git``` ausgetauscht

danach noch innerhalb des Ordner diesen BugFix eingespielt

```git pull origin pull/1863/head```

https://github.com/pyload/pyload/pull/1863/files

**Comment by WtfJoke** [comment]
Jup, git habe ich installiert. Habe das Repo geklont und denn offenen Pull-Request reingezogen, allerdings läuft es nach dem Start nicht mehr...  Das Log, welches man über den Synology Packetzentrum anschauen kann ist leider leer.

Danke vielmals für eure Hilfe und die Infos. :+1:  Jetzt wo ich weiss wo die Einstellungen liegen versuch ich mal die nächsten Tage einen reinstall (setzt mich mal mit dem ipkg weiter auseinander).

Ich mach mal vorerst hier zu. Bei Bedarf würde ich hier wieder einen Comment posten, hoffe ihr würdet mir dann wieder helfen. :smile:

**Comment by b2un0** [comment]
Na du musst halt gucken wo die Ordner bei dir in ```/volume1/@appstore/pyload/pyload``` liegen,

wahrscheinlich musst du das was ich gemacht haben in ```/volume1/@appstore/pyload/``` machen.

**Comment by must4rd** [comment]
wenn du auch die ds213J hast liegt der UpdateManager.py aber unter 
/volume1/@appstore/pyload/var/config/userplugins/hooks.
hab es bei beiden NAS Systemen mit dem installer gemacht (unzureichende.info) und bei deinen war der da. Der Installer erstellt auch noch zudem einen Benutzer names Pyload. Dem musste ich dann noch in der Benutzereinstellung volle Lese und Schreibrechte geben, auch wenn dieser eigentlich deaktiviert ist.

**Comment by WtfJoke** [comment]
Ich hab die ds213 aber da liegt sie am selben Ort und ich habs da auch hingetan.
> /volume1/@appstore/pyload/var/config/userplugins/hooks.

Ich prüfe mal ob ich das Pyload-Paket neuinstallieren kann und dann den Config-Ordner (/volume1/@appstore/pyload/var/config) vorher backupen und dann wieder einspielen kann.

Und ja mit dem ipkg habe ich auch versucht in der Zwischenzeit...  Und da habe ich wirklich grössere Probleme. Da schaffe ich es nicht unter python 2.7 pyCurl zu installieren. pip install pyCurl failt dann weil mit gcc was nicht läuft.

**Comment by WtfJoke** [comment]
So ich habs es jetzt zum laufen gebracht...

Für die Nachwelt:
1. Pyload über Synology-Packetmanager stoppen
2. Pyload mit der neusten Version ersetzt im Ordner /volume1/@appstore/pyload/pyload (egal wie, habs jetzt via git clone gemacht)
3. Über ssh einloggen und Start-Stop Script (das war das fehlende Puzzle-Teil) mit setup aufrufen (Script befindet sich völlig an einem anderen Ort, nämlich hier: /var/packages/pyload/scripts/start-stop-status). 
Befehl lautet also: ./start-stop-status setup

(Merkwürdigerweise kommen noch verwirrende Logmeldungen hinzu, die aber harmlos scheinen)
````/usr/bin/php: symbol lookup error: /volume1/@appstore/pyload/lib/libreadline.so.6: undefined symbol: PC````

4. Und hier halt den Config-Ordner auf den bisherigen Config-Ordner (/volume1/@appstore/pyload/var/config) zurückändern.
5. Pyload via Packetmanager starten --> Alles läuft

Schlussendlich war das Problem nur (nebst, dass ich nicht die neuste Pyload-Version hatte) dass ich dass Setup nicht mehr aufrufen konnte und somit pyload mit einer anderen Config gelaufen ist, bei der nix konfiguriert war. Darum habe ich auch keine Logs gesehen und das Webinterface war nicht konfiguriert.


Danke euch dreien vielmals, auch dass ihr so eine grosse Geduld hattet :sweat_smile:
