### ISSUE TITLE
Fehler bei Windows

### ISSUE THREAD

**Issue by kotarokun** [Gutz-Pilz/pyLoad-stuff#53]
Hey Gutz-Pilz, leider ist das Problem unter Windows, das keine Bash-Scripte ausgeführt werden. 
In deinem Script hast du aber die Passage :
self.pyload.config.setPlugin("FileBot", "exec", 'cd / && ./filebot.sh "{file}"')

die bringt mir aber nix ;) oder sehe ich das falsch?

**Comment by Gutz-Pilz** [comment]
Da kann ich leider nicht weiterhelfen.
Windows habe ich nicht am laufen...vielleicht ist hier irgendwo jemand unter windows unterwegs und kann dir helfen?

**Comment by kotarokun** [comment]
ich meine es währe gut, wenn du vorher das Betriebssystem checken würdest, und wenn es kein Windows ist, dann den Code ausführen, das würde schon perfekt sein :D

**Comment by Gutz-Pilz** [comment]
Du weißt schon das der code nur ausgeführt wird wenn man eine filebot.sh besitzt?
Ich nutze es zB um nach dem verschieben noch 2-3 Prozesse auf/mit der Datei auszuführen.

Wenn du nur mit Filebot verschieben und danach keine extra Aktion brauchst, kannst du den Parameter/Befehl raus löschen.

**Comment by kotarokun** [comment]
nop. das wusste ich nicht.. dachte, das es sonst zu problemen kommen könnte....
kann es leider nicht testen, da mein Share-Online auch noch nicht geht -.-
