### ISSUE TITLE
Sorry not an "Issue" but a "Feature request"

### ISSUE THREAD

**Issue by Youhbi** [Gutz-Pilz/pyLoad-stuff#54]
(Sorry mit Github komm ich nicht so klar, hätte es nen besseren Weg gegeben?)

Hi Gutz

Ich bin von deim Projekt und deiner Ausdauer sehr" angetan", deshalb wage ich es einfach mal dich nach einem Feature zu fragen. :)

Besteht irgendwie die Möglichkeit Filme mittels "HDAreaOrg.py" anhand einer Trakt Liste zu suchen, evtl. sogar die Option "AUSSCHLIESSLICH mittels einer Liste"? Im Idealfall würde es diese danach sogar aus dieser Liste entfernen. --> Edit: Dies könnte man evtl. sogar auch schon durch den Filter "Hide - Collected" in Trakt umgehen.
-- Vielleicht ja eher ein neues Projekt.

Dieses random irgendwelche Filme herunter zu laden ist nicht so mein Fall, ich sauge zwar viel und fast alles so lange die Quali stimmt, aber das ist mir dann doch zu viel :D

Achja... man darf ja wohl noch träumen :P

Weiter so! Gute Arbeit!
Ps: Würde dafür auch gerne ein paar Euronen springen lassen :D

**Comment by feuerwasser85** [comment]
Das wär ein Traum! Bin auch schon lange auf der Suche nach diesem feature. Leider kann der topmoviefetcher nicht mehr mit der trakt.tv API 2.0 umgehen. @Gutz-Pilz: Vielleicht könntest du das nicht mehr supportete Projekt jedoch "recyclen"? https://github.com/topy/python-stuff

**Comment by Youhbi** [comment]
Genau das war auch mein Problem und dann hab ich gesehen, dass Gutz noch fleissig programmiert :)

**Comment by Gutz-Pilz** [comment]
ja. eigtl muss ich fleissig an meinem bachelor arbeiten.
werde aber mal in ner freien stunde mein Glück veruschen

**Comment by Youhbi** [comment]
Oha. Viel Glück!
Ich würd's ja gerne selbst in die Hand nehmen, wäre sogar gelernter Informatiker. Leider aber System Engineer, somit hauptsächlich Infrastruktur und dass bisschen Programmieren das ich beherrsche, würde eher in einem Disaster enden.

**Comment by Gutz-Pilz** [comment]
ich habe mir python auch nur wegen diesem Projekt/ dieser Idee autodidaktisch beigebracht.
Eigentlich studiere ich etwas recht entfernes - aber coden hat mir schon immer Spass gemacht und werde auch mein Bachelor dementsprechend "auslegen"
Ausserdem gibt es bestimmt einiges in meinem Code bei dem sich so mancher eingefleischte Python Experte die Hände überm Kopf zusammen schlagen würde.
Aber es läuft und funktioniert - von daher bin ich zufrieden :smile: 

Probieren geht über studieren :smiley: 
Aber theoretisch habe ich schon eine Suche für die Flexget Nutzer programmiert.
Würde also "nur" noch irgendwie raus finden müssen wie man Trakt ansteuert/ausliest.

**Comment by feuerwasser85** [comment]
@Youhbi :dito. FiSi, bin froh wenn meine kleinen Skripte laufen, aber programmiertechnisch bin ich auch noob.
@Gutz-Pilz :hier die API Doku: http://docs.trakt.apiary.io/#introduction/api-url

**Comment by Youhbi** [comment]
Hättest das in unter einer Minute sowieso gefunden, aber ich poste es trotzdem mal. :) Denke ist sicher ne solide Basis.
http://flexget.com/wiki/Plugins/trakt_list
Ich konnte allerdings ned herausfinden ob das noch die alte API nutzt.

**Comment by Gutz-Pilz** [comment]
Hab mal recherchiert.
Trakt API 2.0 benötigt komische Authentifizierung wo ich nicht komplett dahinter steige.

Scheitere momentan schon am connecten zur trakt api und somit beim auslesen der liste.
Wenn das jemand regeln könnte, wäre ich in der Lage ein Plugin zu schreiben.

**Comment by Youhbi** [comment]
Wie sieht's denn mit dem Flexget Plugin aus dass ich oben gepostet habe? Damit schon probiert?

**Comment by Gutz-Pilz** [comment]
jap. hab ich mir angeschaut.
die benutzen in ihren plugins viele selbst geschriebene librarys.

**Comment by Youhbi** [comment]
Beim durchlesen hab ich mir das wie ein Framework vorgestellt.
Das könnte man aber doch dennoch erweitern nicht? Liste erstellen mit Flexget und allenfalls unabhängig mit Python dann auf diese Daten zugreifen und nutzen. Oder spricht etwas dagegen?

**Comment by Gutz-Pilz** [comment]
ungern will ich flexget als datenermittler einsetzen.
flexget zu installieren ist nicht auf jedem system so einfach

**Comment by Youhbi** [comment]
Ja wie ich es ja selbst schon feststellen durfte :D

**Comment by Gutz-Pilz** [comment]
werde es jetzt so lösen das ich einfach die trakt-liste webseite auslese.
funktioniert auch schon.
jetz gehts drum die namen zu cleanen und auf hdarea zu suchen.

@edit1
hab ich schon gelesen. führt dennoch zu keinem erfolg

@edit2
hab ich auch schon gelesen.
bringt mich leider auch nicht weiter.

irgendwann nächste woche sollte eine erste beta version vorhanden sein

**Comment by Gutz-Pilz** [comment]
läuft größtenteils schon.
muss es die kommende woche dann "nur" noch als pyload plugin umschreiben

**Comment by Gutz-Pilz** [comment]
ausserdem muss ich noch die Datenbank von pyload mit verknüpfen um zu speichern was schon gefunden und geladen wurde.
dat wird also auch noch ein spass ;)

**Comment by Youhbi** [comment]
Wie meinst du aus der Trakt Liste auslesen? Gutes altes URL Scraping?

Wo liegt denn die DB von Pyload? Und wie willst du dppelte Einträge verhindern? IMDB Nr?

**Comment by Youhbi** [comment]
Statt die DB zu verküpfen, wie wäre es einfach mit der Collection Trakt zu vergleichen? Evtl. der einfachere Ansatz, weiss ja nicht wie einfach die DB manipulierbar ist, dafür aber unnötig viele abgleiche mit Trakt. Hmm..

**Comment by Gutz-Pilz** [comment]
Ganz einfach. Wenn ein titel von der traktlist gesucht und auf hdarea gefunden wurde speicher ich mir das in die datenbank.
Beim nächsten mal wird er dann nicht mehr danach suchen...

So mach ich das auch bei den anderen hooks :)

**Comment by Youhbi** [comment]
Und wenn zwei Filme gleich heissen? Gibt's ja. :D Ich meine nur damit ein Film 100% eindeutig identifizierbar ist.

**Comment by Gutz-Pilz** [comment]
da musst du wohl zugeben, dass das sehr sehr selten vorkommt.
mache gerade test mit 20 filmen aus einer traktliste. bis jetzt ist alles richtig was er findet.

wenn ich trakt anbindung hätte. könnte ich natürlich die imdb nummer, die auf hdarea immer per link rauszufinden ist natürlich vergleichen.

So nehm ich jetzt den titel von trakt und such damit auf tmdb.
dort hab ich dann englischen und deutschen titel.
wenn er den deutschen nicht findet, nimmt er den englischen.

funktioniert echt super

**Comment by Youhbi** [comment]
Klingt doch super! :)
Machst es jetzt also ohne API?

**Comment by Gutz-Pilz** [comment]
Also.
wenn ihr wisst wie ein python script ausgeführt und im Vorhinein editiert wird ist hier eine Vorab Betaversion für euch. 
Lediglich um den Prozess abzustecken - habe ich es blanko in python programmiert.

Der Prozess läuft so ab:
Eine Liste der Filme von der Trakt watchlist wird erstellt.
Jeder Eintrag in der Liste wird dann benutzt um auf TMDB den deutschen und den originalen Titel zu bekommen.
Der deutsche Titel eines Filmes wird dann benutzt um auf HDarea zu suchen (mit Berücksichtigung von Quali, Hoster und ungewollten Sachen)
Wenn der deutsche Titel nicht gefunden wird, wird mit dem originalen Titel gesucht.
Wenn dieser dann auch nicht zu finden ist - erstmal Pech gehabt.

So funktioniert momentan das Script.

Die Finale PyloadVersion des Scripts merkt sich was gefunden wurde und sucht es beim nächsten Durchlauf dann natürlich nicht mehr ;)


Das einbinden in pyload werde ich wohl Mittwoch oder Donnerstag erst schaffen.
https://gist.github.com/Gutz-Pilz/8c7490d1030cf55840ff

dort bitte Zeile 4 bis 9 an eure Wünsche anpassen.
zu beachten ihr braucht ein öffentliches Trakt Profil.

Nach Ausführen dürfte die Ausgabe selbsterklärend sein :)

**Comment by Youhbi** [comment]
Sehr cool! Schau ich morgen zwischendurch mal an. Danke für die Mühe! Gib dir noch Feedback. Ma gucken wie das auf nem Synology läuft :)

**Comment by Gutz-Pilz** [comment]
hattest du schon zeit zum testen ?
bin gerade am anpassen für pyload... wollte eigtl tator schauen. der scheint aber doof zu sein :)

**Comment by Youhbi** [comment]
Hi sorry. Nein wollte dir noch schreiben. Hatte heute keine Zeit und bin immer noch mit der Arbeit beschäftigt, morgen finde ich aber bestimmt eine Minute :)) Sorry, ging mir echt unter

**Comment by kotarokun** [comment]
sag mal hat es ein Grund, das du noch auf die alte API zugreifst?? die neue gibt dir auch den entsprechenden IMDB-Title mit :D 

hier mit pyhton-Code alla Copy&Paste  ich habe z.b. meine Listen nicht öffentlich, würde das aber gerne nutzen

**Comment by Gutz-Pilz** [comment]
hast du ein script das api2 ohne riesen aufwand nutzt und ausliest?
wenn ja. schnell her damit ;)

**Comment by kotarokun** [comment]
Erstmal muss ich noch nen bissel Uni-kram machen (leider kein Informatik sondern Medizin... ) ;) aber ich kann mich gerne mal einlesen, aber eigentlich geht das mit den Pin-Verfahren, - du erstellst das über dein Account, dann muss jeder User unter trakt.tv/pin/asdfasdfasdfasdf ein Pin generieren, damit kannst du dir einen spezifischen Pin generiern (3 monate Gültig - in die Text-Datei speicherbar) den nutzt du dann in der Post-Variante und kannst dann auf die Daten zugreifen.... das mit den Einlesen wird nicht sofort passiern

**Comment by Gutz-Pilz** [comment]
@Youhbi 
Kannst morgen direkt die erste pyload version testen ;)
https://github.com/Gutz-Pilz/pyLoad-stuff/blob/master/TraktFetcher.py

**Comment by Youhbi** [comment]
Klasse mach ich.
Funktionen noch die selben oder werden die Links auch schon geaddet? Will dir ja Feedback geben ob alles läuft wie's sollte.

**Comment by Gutz-Pilz** [comment]
was meinst du mit "selben"
Filme werden nach erfolgreichen finden auf hdarea kein zweites mal gesucht. falls du das meinst ;)

**Comment by Youhbi** [comment]
Wie du weiter oben mal beschrieben hast.
- Trakt auslesen
- Auf HDA suchen (+vermerken un DB. Wo liegt die?)
- Zu pyLoad adden

Ist noch mehr? :)

**Comment by Gutz-Pilz** [comment]
so funktionierts...
Die Datenbank verwaltet pyload mit sqlite selbst.
ich nutze nur die pyload internen befehle um diese zu beschreiben und auszulesen.
Die Datei wo alles drin gespeichert wird nennt sich files.db
hab ich aber noch nie anfassen müssen

**Comment by Youhbi** [comment]
Achsoo. Gut ich such mir das mal raus. Das interessiert mich jetzt :D

Aber Funktionsumfang ist ansonsten etwa der oben erwähnte, ja?

**Comment by Gutz-Pilz** [comment]
nicht nur in etwa. 
genau dieser ;)

**Comment by feuerwasser85** [comment]
Vielen Dank! Funktioniert BESTENS!!!
Der Debug gibt gut Auskunft und gefunden sowie geladen hat er auch schon einiges.
Nadelör ist da nur HDArea, da hier die Filme nicht so lange vorrätig sind und schnell wieder offline sind. Was macht das Plugin eigentlich mit Offline links, verwirft es diese Pakete?

**Comment by Gutz-Pilz** [comment]
nein. die werden pyload hinzugefügt.
ich hab im hook kein funktion in der gecheckt wird ob der link noch funktioniert.
Wird also hinzugefügt und pyload muss dann schauen ob der Link noch funktioniert

**Comment by Gutz-Pilz** [comment]
bin schon ganz gespannt auf @kotarokun und seine erfolge mit der api.
das wird dann nochmal eine große schreiberei und ein eingriff in die gesamte logik des hooks.
Aber das hätte dann den vorteil die Filme eindeutig zu identifizieren.

momentan hab ich in etwa 90% trefferquote.
heißt, dass auch tatsächlich der film gefunden wurde, der auch gesucht wird.

**Comment by Youhbi** [comment]
@Gutz-Pilz Besser spät als nie, sorry. Also ich hab jetzt lange hin und her probiert und bei mir (Synology DS1512+) krieg ich's nicht zum laufen. Naja es passiert einfach nichts. Wollte jetzt auch mal versuchen nen Debug anzuschmeissen via Putty, da hab ich dann aber das Problem dass er beim Starten PyCurl nicht importieren kann, da er es nicht findet.. -.-'

**Comment by Gutz-Pilz** [comment]
du bist wirklich komplett up-to-date mit dem pyload code.
momentan bestehen genau diese probleme mit all meinen hooks.

**Comment by Youhbi** [comment]
Ja, 0.49 :/

**Comment by kotarokun** [comment]
@Gutz-Pilz  das ist estmal ein vorschlag bzw Anfang. https://gist.github.com/kotarokun/c2374d9bc6022d9c0827/edit

**Comment by Gutz-Pilz** [comment]
@Youhbi 
0.49 ist / hat jeder.
weil immer wieder bugs mit den Updates einhergehen hab ich den Updatemanager deaktiviert und hab somit manche Bugs die auch mit meinen hooks dann im zusammenspiel mit pyload updates entstehen nicht auf dem Schirm.

**Comment by Gutz-Pilz** [comment]
Habs geschafft treaktapi anzusteuern.
ziemlich kompliziert sag ich euch :)
Aber dadruch bekomme ich die tmdb-id nummer mit dieser ich dann wiederum eideutig die namen auf tmdb erhalten

**Comment by Gutz-Pilz** [comment]
Falls mich also jemand unterstützen will.
https://gist.github.com/Gutz-Pilz/e78ac8a10bd8e9699454
^^hier ist mein Anfang

**Comment by kotarokun** [comment]
Ich hoffe ich konnte dir schon mal etwas helfen das du da das auch verstanden habe. Ich würde gerne nochmal mit weiter Schauen. Was ist denn als nächstes geplant oder brauchst du für etwas Hilfe?

Außerdem ist der totale Vorteil man muss seine Listen nicht öffentlich zugänglich machen sondern kann diese privat lassen und vielleicht eine eigene Film Liste machen für die zu ladenden Filme. Seid dem es mit Flexget nicht so gut klappt.

**Comment by Gutz-Pilz** [comment]
Leider stimmt das mit den Provaten listen leider nicht.
ich muss meine öffentlich machen um sie per api auszulesen

**Comment by Gutz-Pilz** [comment]
Ja. dein Code hat einiges zum gelingen beigetragen!
dass bei jedem request der Refresh token wieder generiert und mitgegeben werden muss...ist ziemlich umständlich.

Ich müsste noch eine Abfrage machen, ob der token jetzt abgelaufen ist.
das habe ich momentan halt noch nicht...
weiß auch auf anhieb nicht wie man sowas bewerkstelligen könnte

**Comment by kotarokun** [comment]
Ganz bestimmt kann man das machen. Kannst du nicht eigentlich eine singen sqlite Tabelle erstellen oder wirklich über die Textdatei mit einem Timestamp hinterlegen. Das geht ja easy :) oder du trennst die beiden Infos mit einem Sonderzeichen. Dann kannst du sie ja mit re wieder auslesen zu dem Code

**Comment by Gutz-Pilz** [comment]
DANKE!
Getan - funktioniert
Hab jetzt mal weiter programmiert. dürfte morgen abend für pyload fertig sein.
Am schönsten find ich den den IMDB-ID abgleich. 
so ist man dann 100% sicher das auch der richtige film ist ;)
