### ISSUE TITLE
FileBot/SJ:No module named Hook 

### ISSUE THREAD

**Issue by pahofmann** [Gutz-Pilz/pyLoad-stuff#55]
I've put both scripts in: /etc/pyload/userplugins/hooks and get the error FileBot/SJ:No module named Hook when restarting.
I've seen issue #51 but it does not seem related.
I'm running pyload 0.4.9 installed from arch-aur. It uses python 2.7.10 and /etc/pyload is listed at the config folder.

**Comment by Gutz-Pilz** [comment]
du hast wahrscheinlich nicht die neuesten github files.
und der updater funktioniert leider nicht.
tausche die "UpdateManager.py" datei im hooks ordner mit dieser.
https://raw.githubusercontent.com/pyload/pyload/c3b3f3ea5c813edbe3e6941c535c78ad494244ee/module/plugins/hooks/UpdateManager.py

**Comment by raidyne** [comment]
hallo,
leider gleiches problem, selbst mit besagter "UpdateManager.py" datei im hooks ordner.

war aber auch vorher nicht vorhanden dort...

**Comment by pahofmann** [comment]
@Gutz-Pilz nachdem ich den UpdateManager gegen die gepostete Version ausgetauscht habe sehe ich folgenden fehler im Log: 	Error importing UpdateManager: No module named Addon.

**Comment by raidyne** [comment]
welche version hast du installiert? ich habe die stable.zip aus dem pyload-github-repo

**Comment by pahofmann** [comment]
Installiert über archlinux aur. Sollte die gleiche version sein.

**Comment by Gutz-Pilz** [comment]
ja. aber die git source ist aktueller...
schau mal hier...da hatte jemand das gleiche problem
https://github.com/Gutz-Pilz/pyLoad-stuff/issues/51

**Comment by pahofmann** [comment]
Den issues  hatte ich ja oben verlinkt.  Download+erstezen hat leider nicht funktioniert.

**Comment by Gutz-Pilz** [comment]
Probier es jetzt nochmal

**Comment by acidburn78** [comment]
Hallo Gutz-Pliz,

unter SJ.py ist jetzt der Code vom TractFetcher, bitte wieder ändern

**Comment by Gutz-Pilz** [comment]
sorry!
getan

**Comment by Gutz-Pilz** [comment]
@pahofmann 
Funktioniert es mittlerweile ?

**Comment by pahofmann** [comment]
Noch keine Zeit zum testen gehabt leider. Werde aber nacher noch dazu kommen und ggf.  Nochmal  neu installieren um zusehen ob ich den Update manager zum laufen bekomme.

**Comment by pahofmann** [comment]
Habe die neuste Version aus dem git ausgecheckt. Hier werden die Hooks geladen aber ich erhalte folgenden Fehler beim start: Error executing hooks: 'SerienjunkiesOrg
Und wenn der FIlebotHook ausgefuhrt werden sollte:  WARNING Error calling event handler package_extracted: >, (,), 'FileBot' object has no attribute 'getConfig' 
Desweiteren wird python-pillow dort nicht mehr fuer die Captcha recognition erkannt.

Welche Version verwendest du aktuell?
Habe mittlerweile die Version aus dem AUR, stable branch und master durch und keine scheint zu funktionieren.

**Comment by Gutz-Pilz** [comment]
Okay. tatsächlich. auf featurewunsch hab ich gestern eine alte funktion wieder hinzugefügt.
fehler ist behoben. filebot sollte jetzt laufen.
Captcha scheinen momentan generell nicht zu funktionieren.
SerienJunkiesOrg ist der Crypter für serienjunkies links.
meine Version funktioniert (glaube ich)
werde sie nachher mal posten

**Comment by acidburn78** [comment]
Hallo Gutz-Pliz, an deinem SerienJunkies Crypter wäre ich auch interessiert. Nutze aktuell den aus dem Pyload.org-Forum aber bei dem werden in meiner Config die Einstellungen nicht gespeichert. Nehme immer die Einstellung "Take SJ Name: Show" nach nem pyload Neustart steht es aber immer wieder auf "Packagename"

**Comment by Gutz-Pilz** [comment]
aso. das liegt vielleicht auch ein meiner SJ.py
lösche dort mal
https://github.com/Gutz-Pilz/pyLoad-stuff/blob/master/SJ.py#L113-L114
^
- diese zeilen heraus löschen
- Crypter neu einstellen
- pyload neustarten

**Comment by acidburn78** [comment]
Haha und ich wundere mich die ganze Zeit wo die Einstellung her kommt!!! Dann kann ich es ja auch einfach in der SJ.py ändern auf Show!! Danke für den Hinweis war schon langsam am verzweifeln

**Comment by Gutz-Pilz** [comment]
ja. das problem hatte ich auch immer wieder. deswegen wird bei jedem pyload start jetzt auf packagename gesetzt.
somit findet filebot auch immer den richtigen namen

**Comment by acidburn78** [comment]
Ich habe dann wenn ich es auf Packagename stehen habe nur das Problem das alles in den Ordner mit dem Namen des Hosters gedownloaded wird, also Ordnername ist dann bei mir immer shareonline.biz und der Name des Packets ebenfalls. Somit kommt bei Filebot oft die Meldung das im Ordner noch Archive vorhanden sind. da die zu einem anderen Download gehören.

**Comment by Gutz-Pilz** [comment]
komisch. 
ja dann stell auf Show um ;)

**Comment by b2un0** [comment]
@acidburn78 dann scheint aber was mit deinem SJ-Decrypter Plugin nicht zu stimmen, welche Version hast du davon?
Das hier ist meine http://pastebin.com/TLRFEshy
Die funktioniert bei mir im zusammenspiel mit SJ.py von @Gutz-Pilz einwandfrei.

**Comment by acidburn78** [comment]
@b2un0 das müsste die aus dem Pyload-Forum sein, so nach dem groben drüberfliegen. Die habe ich auch am laufen. Eventuell habe ich irgendwo noch ne falsche Einstellung warum er den Namen des Hosters für Packet und Ordner übernimmt. Die Archive die er runterlädt behalten Ihren Namen

**Comment by pahofmann** [comment]
Super, FileBot läuft jetzt.
Man könnte in der config vllt. noch erwähnen dass man bei series/movie destination nicht nur Pfad sondern auch das Format angeben muss. Aber der fehler war schnell gefunden.

Mir ist gerade aufgefallen das in der neusten Version die ich geladen habe kein SerienJunkiesOrg crypter dabei ist.
Könntest du deine funktionierende Version davon evtl posten?

**Comment by acidburn78** [comment]
@pahofmann im Post von b2un0 findest du den Crypter ist der Link von pastebin Code rauskopieren und unter userplugins/crypter ne neue Datei erstellen SerienjunkiesOrg.py und den Code reinkopieren

**Comment by pahofmann** [comment]
Danke, teste ich gleich.
Gerade gesehen der Fehler wegen dem Format könnte auch vom vergessenen trailing / am Ende des Pfads kommen.

**Comment by pahofmann** [comment]
Serienjunkies an sich geht wieder. Leider erhalte ich beim start noch einen Fehler mit der neusten SJ.py:
271	15.10.2015 15:04:56	ERROR	Traceback (most recent call last):
272	? 	?	File "/opt/pyload/pyLoadCore.py", line 667, in
273	? 	?	main()
274	? 	?	File "/opt/pyload/pyLoadCore.py", line 658, in main
275	? 	?	pyload_core.start()
276	? 	?	File "/opt/pyload/pyLoadCore.py", line 469, in start
277	? 	?	self.scheduler.work()
278	? 	?	File "/opt/pyload/module/Scheduler.py", line 85, in work
279	? 	?	j.start()
280	? 	?	File "/opt/pyload/module/Scheduler.py", line 111, in start
281	? 	?	self.run()
282	? 	?	File "/opt/pyload/module/Scheduler.py", line 101, in run
283	? 	?	ret = self.call(*self.args, **self.kwargs)
284	? 	?	File "/opt/pyload/module/plugins/internal/Addon.py", line 117, in _periodical
285	? 	?	self.periodical()
286	? 	?	File "/etc/pyload/userplugins/hooks/SJ.py", line 119, in periodical
287	? 	?	self.pattern = "|".join(getSeriesList(self.get_config("file"))).lower()
288	? 	?	File "/etc/pyload/userplugins/hooks/SJ.py", line 22, in getSeriesList
289	? 	?	self.core.log.error("Abbruch, Suchdatei wurde nicht gefunden!")
290	? 	?	NameError: global name 'self' is not defined

**Comment by Gutz-Pilz** [comment]
Hast du eine SJ.txt angelegt und angegeben ?

**Comment by Gutz-Pilz** [comment]
Filebot hätte aber auch in klartext ohne debug in den log geschrieben.
ich glaube das hast du "abgeschnitten"

**Comment by pahofmann** [comment]
Okay doofer Fehler sorry. Die SJ.txt war im pyload config nicht im install folder.

**Comment by pahofmann** [comment]
Zu früh gefreut. Zwar keine Fehler mehr im Log und es wird auch bei den activated modules aufgelistet, aber es wird nichts hinzugefügt. Auch keine Meldungen im Log das gesucht wird, falls es da welche schreibt.

**Comment by Gutz-Pilz** [comment]
http://www.hannesmueller.com/pyload.tar.gz

^^probier mal meine pyloadversion

**Comment by pahofmann** [comment]
Wenn ich den kompletten pylado Ordner durch meinen austausche nummt pyload beim start an es würde gerade zum ersten mal starten.

**Comment by Gutz-Pilz** [comment]
du musst aus deinem alten die conf dateien rüber kopieren.

**Comment by Gutz-Pilz** [comment]
account conf.
plugin.conf
pyload.conf

**Comment by pahofmann** [comment]
Okay damit startet er wieder, aber immer noch das gleiche, nicht auffälliges im log(http://pastebin.com/n1JshP91). Aber er scheint nicht zu suchen.

**Comment by Gutz-Pilz** [comment]
starte mal im debugmodus.

**Comment by pahofmann** [comment]
Auch nichts weiter relevantes leider.
Werden bei jedem Surchdurchlauf normalerweise Logeinträge geschrieben?
Oder taucht einfach nichts im Log auf falls er nichts findet?

**Comment by Gutz-Pilz** [comment]
nein. selbst dann schreibt er was rein.
kann ich trotzdem mal den debuglog sehen ?

**Comment by pahofmann** [comment]
https://gist.github.com/pahofmann/e5ab5d57bb975f3290ec

**Comment by Gutz-Pilz** [comment]
mh. ich bin mit meinem latein am ende. keine ahnung was da los ist

**Comment by Gutz-Pilz** [comment]
welche python version hast du denn ?

**Comment by pahofmann** [comment]
`python --version`: 3.5.0 
In der pyload config steht: 2.7.10

**Comment by pahofmann** [comment]
Habe mit deiner Version gerade nochmal versucht SJ Links manuell zu laden, dabei kommt der Fehler:
failed'NoneType' object has no attribute 'SerienjunkiesOrg' 0.00 BSerienjunkiesOrg
Werde also wohl wieder auf meine Version zurückgehen und schauen ob ich noch etwas finde wieso die Suche nicht gestartet wird.
