### ISSUE TITLE
donate button

### ISSUE THREAD

**Issue by b2un0** [Gutz-Pilz/pyLoad-stuff#56]
Der Donate button in der Readme MD unten funktioniert nicht.

der sollte in etwa so aussehen

https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2HRQPARE3C7DG

einfach hinten die hosted_button_id in deine korrigieren.

**Comment by Gutz-Pilz** [comment]
Danke - ist mir echt nicht aufgefallen!
