### ISSUE TITLE
unsorted flag

### ISSUE THREAD

**Issue by b2un0** [Gutz-Pilz/pyLoad-stuff#57]
hey,

kannst du den "unsorted" flag bitte wieder mit in die FileBot.py rein nehmen?

https://bitbucket.org/b2un0/pyload-hook-filebot/raw/97073abaddcb2b4d7a19eb3727ed4430fe305344/FileBot.py

das macht das nach arbeiten einfacher, danke

**Comment by Gutz-Pilz** [comment]
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/db74ec194002711a4c3d940e052767e717ba7096

Done ;)

**Comment by b2un0** [comment]
besten dank, aber kontrollier noch mal die VersionNummer der FileBot.py, meine letzte hatte 1.4, die jetzt 1.3?!

**Comment by Gutz-Pilz** [comment]
DOne ;)
