### ISSUE TITLE
FileBot Fehler

### ISSUE THREAD

**Issue by b2un0** [Gutz-Pilz/pyLoad-stuff#58]
ich hab vorhin mal den UpdateManager laufen lassen, geht noch alles, bis auf deine Plugins.

```
WARNING Error calling event handler package_extracted: >, (,), package_extracted() takes exactly 3 arguments (2 given)
WARNING Error calling event handler package_extracted: >, (,), 'FileBot' object has no attribute 'getConfig'
```
die zweite Zeile ist irrelevant da durch die erste ausgelöst.

**Comment by Gutz-Pilz** [comment]
hab ein update gemacht.
müsste jetzt wieder gehen
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/4da9a42ff0b9e5525118d01f48d0be0c087b7271#diff-3ac36d2493145772b7cc2f037bf7a27f

**Comment by b2un0** [comment]
Die Version hatte ich schon automatisch nach dem Neustart durch den UpdateManager, gerade noch mal neugestartet:

````
15.10.2015 16:56:29	pyLoadStuff-Updater	Local FileBot-Hook is latest: 1.6
15.10.2015 16:56:29	pyLoadStuff-Updater	Local SJ-Hook is latest: 2.4
15.10.2015 16:56:29	pyLoadStuff-Updater	Local HDAreaOrg-Hook is latest: 2.7
```

Ich guck mal ob das gleich nochmal passiert..

**Comment by b2un0** [comment]
Ach, ich seh schon, Zeile #1 wurde durch meine eigene ```AppleDeviceNotify``` verursacht, sorry!

http://forum.pyload.org/viewtopic.php?p=19896#p19896
