### ISSUE TITLE
HOOK Filebot: Failure (°_°)

### ISSUE THREAD

**Issue by raidyne** [Gutz-Pilz/pyLoad-stuff#60]
hallo,

leider erhalte ich immer noch einen fehler, wenn der Fileboot Hook ausgeführt wird:

15.10.2015 17:27:46	DEBUG	HOOK FileBot: MKV-Checkup (package_extracted)
389	15.10.2015 17:27:46	DEBUG	HOOK FileBot: Hier sind keine Archive
390	15.10.2015 17:27:46	INFO	HOOK FileBot: plex refreshed at 
391	15.10.2015 17:27:46	INFO	HOOK FileBot: executed
392	15.10.2015 17:27:57	INFO	HOOK FileBot: Locking /home/nutzer/filebot/logs/amc.log
393	15.10.2015 17:27:57	INFO	HOOK FileBot: Run script [fn:amc] at [Thu Oct 15 17:27:54 CEST 2015]
394	15.10.2015 17:27:57	INFO	HOOK FileBot: Parameter: exec = cd / && ./filebot.sh "{file}"
395	15.10.2015 17:27:57	INFO	HOOK FileBot: Parameter: clean = y
396	15.10.2015 17:27:57	INFO	HOOK FileBot: Parameter: skipExtract = y
397	15.10.2015 17:27:57	INFO	HOOK FileBot: Parameter: excludeList = pyload-amc.txt
398	15.10.2015 17:27:57	INFO	HOOK FileBot: Parameter: reportError = n
399	15.10.2015 17:27:57	INFO	HOOK FileBot: Parameter: unsorted = n
400	15.10.2015 17:27:57	INFO	HOOK FileBot: Parameter: storeReport = n
401	15.10.2015 17:27:57	INFO	HOOK FileBot: Parameter: artwork = y
402	15.10.2015 17:27:57	INFO	HOOK FileBot: Parameter: subtitles = en
403	15.10.2015 17:27:57	INFO	HOOK FileBot: Parameter: pushbullet = *****
404	15.10.2015 17:27:57	INFO	HOOK FileBot: Parameter: plex = 192.168.0.1
405	15.10.2015 17:27:57	INFO	HOOK FileBot: Parameter: extras = n
406	15.10.2015 17:27:57	INFO	HOOK FileBot: Argument: /srv/data/downloads/xyz
407	15.10.2015 17:27:57	INFO	HOOK FileBot: Failure (°_°)
408	15.10.2015 17:27:57	INFO	HOOK FileBot:
409	15.10.2015 17:27:57	INFO	HOOK FileBot: cleaning
410	15.10.2015 17:27:57	INFO	HOOK FileBot: kein Ordner zum cleanen vorhanden

der debug-log gibt auch nicht mehr her...

**Comment by Gutz-Pilz** [comment]
du kannst hier mal noch schauen.
/home/nutzer/filebot/logs/amc.log

ansonsten mal filebot manuell laufen lassen.
vielleicht ist das dann aufschlussreicher

**Comment by raidyne** [comment]
ja, war in der tat ein filebot problem. cache leeren hat geholfen.
