### ISSUE TITLE
ERROR bei aktuellem SJ.py

### ISSUE THREAD

**Issue by DKeppi** [Gutz-Pilz/pyLoad-stuff#61]
Bekomme leider folgenden ERROR
pyload ist aktuell...

ERROR	HOOK SJ: Error executing periodical task: local variable 'storage' referenced before assignment
311	16.10.2015 07:29:01	ERROR	Traceback (most recent call last):
312	?	?	File "/volume1/@appstore/pyload/pyload/pyLoadCore.py", line 667, in
313	?	?	main()
314	?	?	File "/volume1/@appstore/pyload/pyload/pyLoadCore.py", line 654, in main
315	?	?	deamon()
316	?	?	File "/volume1/@appstore/pyload/pyload/pyLoadCore.py", line 646, in deamon
317	?	?	pyload_core.start()
318	?	?	File "/volume1/@appstore/pyload/pyload/pyLoadCore.py", line 469, in start
319	?	?	self.scheduler.work()
320	?	?	File "/volume1/@appstore/pyload/pyload/module/Scheduler.py", line 85, in work
321	?	?	j.start()
322	?	?	File "/volume1/@appstore/pyload/pyload/module/Scheduler.py", line 111, in start
323	?	?	self.run()
324	?	?	File "/volume1/@appstore/pyload/pyload/module/Scheduler.py", line 101, in run
325	?	?	ret = self.call(*self.args, **self.kwargs)
326	?	?	File "/volume1/@appstore/pyload/pyload/module/plugins/internal/Addon.py", line 117, in _periodical
327	?	?	self.periodical()
328	?	?	File "/volume1/pyload/userplugins/hooks/SJ.py", line 171, in periodical
329	?	?	self.range_checkr(link,title)
330	?	?	File "/volume1/pyload/userplugins/hooks/SJ.py", line 195, in range_checkr
331	?	?	self.parse_download(link, title)
332	?	?	File "/volume1/pyload/userplugins/hooks/SJ.py", line 221, in parse_download
333	?	?	self.send_package(title,items) if len(items) > 0 else True
334	?	?	File "/volume1/pyload/userplugins/hooks/SJ.py", line 228, in send_package
335	?	?	if storage == 'downloaded':
336	?	?	UnboundLocalError: local variable 'storage' referenced before assignment

**Comment by b2un0** [comment]
see #59

**Comment by DKeppi** [comment]
Danke!
