### ISSUE TITLE
Failed to receive SOCKS5 connect request ack.

### ISSUE THREAD

**Issue by b2un0** [Gutz-Pilz/pyLoad-stuff#63]
Hey,

kannst du mal schauen ob deine Hooks die proxy funktion von pyLoad mit verwenden?

Ich verwende immer wieder mal einen Socks5 Proxy (ssh tunnel auf einen root server) sobald ich bei KD am Tageslimit angekommen bin.

Sobald der Proxy im pyLoad auf "an" steht, kommt folgender Fehler.

```
19.10.2015 17:12:37	ERROR	HOOK SJ: Error executing periodical task: (7, 'Failed to receive SOCKS5 connect request ack.')
10288	19.10.2015 17:12:37	ERROR	Traceback (most recent call last):
10289	?	?	File "/usr/bin/pyLoadCore", line 667, in
10290	?	?	main()
10291	?	?	File "/usr/bin/pyLoadCore", line 654, in main
10292	?	?	deamon()
10293	?	?	File "/usr/bin/pyLoadCore", line 646, in deamon
10294	?	?	pyload_core.start()
10295	?	?	File "/usr/bin/pyLoadCore", line 469, in start
10296	?	?	self.scheduler.work()
10297	?	?	File "/usr/share/pyload/module/Scheduler.py", line 85, in work
10298	?	?	j.start()
10299	?	?	File "/usr/share/pyload/module/Scheduler.py", line 111, in start
10300	?	?	self.run()
10301	?	?	File "/usr/share/pyload/module/Scheduler.py", line 101, in run
10302	?	?	ret = self.call(*self.args, **self.kwargs)
10303	?	?	File "/root/.pyload/userplugins/internal/Addon.py", line 118, in _periodical
10304	?	?	self.periodical()
10305	?	?	File "/root/.pyload/userplugins/hooks/SJ.py", line 158, in periodical
10306	?	?	self.range_checkr(link,title)
10307	?	?	File "/root/.pyload/userplugins/hooks/SJ.py", line 195, in range_checkr
10308	?	?	self.parse_download(link, title)
10309	?	?	File "/root/.pyload/userplugins/hooks/SJ.py", line 210, in parse_download
10310	?	?	req_page = getURL(series_url)
10311	?	?	File "/usr/share/pyload/module/network/RequestFactory.py", line 122, in getURL
10312	?	?	return pyreq.getURL(*args, **kwargs)
10313	?	?	File "/usr/share/pyload/module/network/RequestFactory.py", line 67, in getURL
10314	?	?	rep = h.load(*args, **kwargs)
10315	?	?	File "/usr/share/pyload/module/network/HTTPRequest.py", line 203, in load
10316	?	?	self.c.perform()
10317	?	?	error: (7, 'Failed to receive SOCKS5 connect request ack.')
```

**Comment by Gutz-Pilz** [comment]
boah. keine ahnung wie das geht ;)
Hat KD wirklich ne gedrosselte Leitung  -  scheisse!

**Comment by b2un0** [comment]
ja kp, vielleicht mal in den anderen hooks schauen wie die http requests absenden, du verwendest ja glaub ich python nativen code wie curl, die urllib usw..

KD drosselt in stark belasteten Segmenten ab ~60GB/Tag diverse OCH mittels  [DPI](https://de.wikipedia.org/wiki/Deep_Packet_Inspection).
Wenn ich dann auf einen Socks5 SSH Tunnel umstellen hab ich wieder meine  :100:Mbit

**Comment by b2un0** [comment]
Der UpdateManager.py verwendet self.load(...) welche hier definiert ist

https://github.com/pyload/pyload/blob/stable/module/plugins/internal/Plugin.py#L202

Vielleicht auch ein Ansatz für dich? Ansonsten guck ich mir das selber mal irgendwann an.

**Comment by b2un0** [comment]
Ich hab gerade gemerkt das meine AppleDeviceNotify.py ebenfalls nicht den pyLoad request service verwendet, der funktioniert auch nicht wenn ich den Proxy an habe. Ich bau das ding da mal ein und guck wie sich das verhält.

**Comment by Gutz-Pilz** [comment]
und ?
warst du erfolgreich ?

**Comment by b2un0** [comment]
Bisher noch nicht dazu gekommen.

Am Dienstag, 20. Oktober 2015 schrieb Gutz-Pilz :

> und ?
> warst du erfolgreich ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gutz-Pilz/pyLoad-stuff/issues/63#issuecomment-149609794>
> .
>


-- 

Freundliche Grüße / Kind regards

Branko Wilhelm

*Software-Developer*
*z-index development, **Hamburg, Germany*

**Comment by b2un0** [comment]
In meiner AppleDeviceNotify.py hab ich es jetzt drin.
https://bitbucket.org/b2un0/pyload-ios-push/raw/133f982200ce282ad61e703327656b0b2e3b00a8/AppleDeviceNotify.py

Orientiert hab ich mich an der TransmissionRPC.py welche auch self.load() verwendet, in jener Datei sieht man auch noch wie man custom header setzen kann (die konnte ich weg lassen, geht auch ohne).

**Comment by Gutz-Pilz** [comment]
kannst du mal traktfetcher testen ?
der müsster jetzt auch die pyload interne librarys nutzen

**Comment by b2un0** [comment]
Ich benutze Trakt nicht wirklich.

Interessant sind vielleicht auch für dich die beiden neuen Hooks "Pushover" und "PushBullet"

https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/PushOver.py
https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/PushBullet.py
