### ISSUE TITLE
Feature: Export results in a textfile

### ISSUE THREAD

**Issue by namealwaysinuse** [Gutz-Pilz/pyLoad-stuff#64]
Hey gutz,

ist es evtl möglich, dass du die SJ.py und HDAreaOrg.py so modifizierst, dass sie die Ergebnisse in eine Textdatei schreiben?

Würde die Hooks gerne für JDownloader nutzen =)

Gruss

**Comment by feuerwasser85** [comment]
theoretisch müsstest du nur nen SQL SELECT FROM als Skript ausführen von der files.db, dann kannst dus in ein Textfile speichern.

**Comment by namealwaysinuse** [comment]
ansich hast du recht, aber dann muesste ich Pyload immer noch am Laufen haben oder?
Mir gehen diese dauernden unueberlegten Updates von pyload extrem auf die Nerven und JDownloader kann eigentlich das "selbe" nur etwas anders geloest.

Im moment nutze ich FlexGet fuer Serien und Filme, jedoch gibt es fuer Filme keinen vernuenftigen RSS Feed und genau hier treffen die PythonScripte direkt ins schwarze.

**Comment by b2un0** [comment]
Nein, es handelt sich um eine sqlite Datei, die kannst du mit jedem sqlite client auslesen.

Update pyLoad einmal auf den jetzt aktuell laufenden Stand und deaktivere den UpdateManager -> fertig.

**Comment by namealwaysinuse** [comment]
D. h. 

python SJ.py aus dem Terminal schreibt ohne pyload in deine Datenbank?

Ich hatte den UpdateManager bei mir deaktiviert und trotzdem waren auf einmal meine ganzen hooks weg...

Ausserdem ging doch der 9kw hook auch nicht mehr oder?

**Comment by b2un0** [comment]
ne, das nicht, SJ.py ist ja an die pyLoad internen Methoden gebunden.

Bei mir geht seit dem letzten Update von vor ca einer Woche wieder alles, seit dem hab ich den UpdateManager aus und es läuft wie es soll, inkl der Hooks von @Gutz-Pilz

**Comment by namealwaysinuse** [comment]
Ok also vor 4 Tagen ging 9KW bei mir nicht und share-online hat sich nach ein paar Downloads auf ungueltig gestellt. Deswegen ja der wechsel zu JD.. :S

**Comment by Gutz-Pilz** [comment]
bin auf dem neusten stand
bei mir läuft alles wunderbar.
