### ISSUE TITLE
TraktFetcher: No module named requests

### ISSUE THREAD

**Issue by feuerwasser85** [Gutz-Pilz/pyLoad-stuff#65]
Pyload bringt seit Neuestem `Error importing TraktFetcher: No module named requests` beim starten von TraktFetcher.

**Comment by Gutz-Pilz** [comment]
hast du python requests installiert ?
falls nicht 
```pip install requests```

**Comment by feuerwasser85** [comment]
Hab leider kein pip, das läuft auf ner Synology. Python Paket 2.7.3 (default, Feb 10 2013, 02:59:30) [GCC 4.2.1]

**Comment by feuerwasser85** [comment]
bin jetzt schon einen guten Schritt weiter. (better google before write)
pip freeze sagt "requests==2.7.0". Liegt es im falschen Verzeichnis? Muss ich noch Systemvariablen setzen?

**Comment by feuerwasser85** [comment]
Hab jetzt mal das PythonModule Paket deinstalliert, mit pip install requests das Modul nochmal installiert, aber es wird immer noch nicht angesprochen.

**Comment by Gutz-Pilz** [comment]
Okay. lass die finger vom system...
ich habs gemanaged bekommen dsa TraktFetcher nun pyload eigene librarys nutzt.
Fix komm in 5 min

**Comment by Gutz-Pilz** [comment]
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/fe88b91088b2a857d598d1202a53025b49001f13#diff-3e740fc1f37a99fcd2c2ad6449af168f

**Comment by feuerwasser85** [comment]
Funktioniert jetzt wieder, danke!
Allerdings bricht er nach ein paar gefundenen files ab mit `Error executing periodical task: 'unicode' object has no attribute 'getText'´`

**Comment by Gutz-Pilz** [comment]
das problem ist bestimmt an ein bestimmten Buchstaben/Zeichen in einem Titel gekoppelt.

kannst du mir bitte den vollen log geben!

**Comment by feuerwasser85** [comment]
`106	DEBUG	ADDON TraktFetcher: LOAD URL https://api.themoviedb.org/3/search/movie?api_key=4e33dc1073b5ad87851d8a4f506dc096&query=Self/less&language=de | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
107	DEBUG	ADDON TraktFetcher: Suche "Self/Less Der Fremde in mir" auf HDArea
108	DEBUG	ADDON TraktFetcher: keine Suchergebnisse mit deutschem Titel gefunden: "Self/Less Der Fremde in mir"
109	DEBUG	ADDON TraktFetcher: suche mit englischem Titel: Self/less
110	DEBUG	ADDON TraktFetcher: LOAD URL https://api.themoviedb.org/3/search/movie?api_key=4e33dc1073b5ad87851d8a4f506dc096&query=The%20Hunger%20Games%20Mockingjay%20Part%202&language=de | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
111	DEBUG	ADDON TraktFetcher: Suche "Die Tribute von Panem Mockingjay Teil 2" auf HDArea
112	DEBUG	ADDON TraktFetcher: keine Suchergebnisse mit deutschem Titel gefunden: "Die Tribute von Panem Mockingjay Teil 2"
113	DEBUG	ADDON TraktFetcher: suche mit englischem Titel: The Hunger Games Mockingjay Part 2
114	DEBUG	ADDON TraktFetcher: LOAD URL https://api.themoviedb.org/3/search/movie?api_key=4e33dc1073b5ad87851d8a4f506dc096&query=Hitman%20Agent%2047&language=de | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
115	DEBUG	ADDON TraktFetcher: Suche "Hitman Agent 47" auf HDArea
116	ERROR	ADDON TraktFetcher: Error executing periodical task: 'unicode' object has no attribute 'getText'`

**Comment by Gutz-Pilz** [comment]
Okay. krass... kann den fehler auf die schnelle grad nicht korrigieren.
Entferne Hitman 47 
das dürfte erstmal eine temporäre lösung sein.

**Comment by feuerwasser85** [comment]
Hab mal ein bisschen mit der Liste rumgespielt, erst dachte ich es liegt an Doppelpunkten im Titel, aber bei The Gunman wurde ich nervös :-). Das Einzige, was mir auffällt ist, dass er (reproduzierbar) beim suchen des vierten Films abbricht.

**Comment by joberreiter** [comment]
Die Doku zu BeautifulSoup bringt des Rätsels Lösung: .gettext() -> .get_text() oder .string

**Comment by Gutz-Pilz** [comment]
hab ich auch schon ausprobiert...
  File "/root/.pyload/userplugins/hooks/TraktFetcher.py", line 93, in periodical
    title = title.get_text()
TypeError: 'NoneType' object is not callable

**Comment by joberreiter** [comment]
Probier mal einfach `.string`, also 
```
# Get Trakt Watchlist Titles
for element in soup.select("div[class=titles] > h3"):
    self.log_debug("Watchlist title found: %s" % element)
    title = element.string
    title = replaceUmlauts(html_parser.unescape(title))
...
```

**Comment by feuerwasser85** [comment]
Gibts Neuigkeiten zu TraktFetcher? Hab mal rumprobiert mit .string aber da kommt:
`ADDON TraktFetcher: Error executing periodical task: 'unicode' object has no attribute 'string'`
Funktioniert TraktFetcher bei jemandem?

**Comment by Gutz-Pilz** [comment]
Werde wohl erst nächstes jahr april wieder daran arbeiten können.

feuerwasser85 <notifications@github.com> schrieb am Mo., 30. Nov. 2015 um
21:01:

> Gibts Neuigkeiten zu TraktFetcher? Hab mal rumprobiert mit .string aber da
> kommt:
> ADDON TraktFetcher: Error executing periodical task: 'unicode' object has
> no attribute 'string'
> Funktioniert TraktFetcher bei jemandem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gutz-Pilz/pyLoad-stuff/issues/65#issuecomment-160742025>
> .
>
-- 
- von unterwegs -

**Comment by feuerwasser85** [comment]
Ok. Vielleicht sind meine skills bis dahin auch ein bisschen mehr geworden und ich habs selbst rausgefunden ;-)
Gute Zeit bis dahin!
