### ISSUE TITLE
Incorrect padding

### ISSUE THREAD

**Issue by must4rd** [Gutz-Pilz/pyLoad-stuff#66]
Hi hab seit 2-3 Wochen immer wieder eine Fehlermeldung von HDarea und SJ Hook.

24.10.2015 12:48:18	ERROR	HOOK SJ: Error performing periodical task | Incorrect padding

Ist der Fehler bekannt oder muss ich bei mir gucken was da genau nicht stimmt?

**Comment by Gutz-Pilz** [comment]
Fehler stammt von pyload.
Leider nicht von meinen hooks :)

**Comment by must4rd** [comment]
ok gut zu wissen xD

**Comment by Gutz-Pilz** [comment]
Hast du ein funktionierenden Updatemanager ?
oder hast du ihn ausgeschaltet ?

**Comment by must4rd** [comment]
ich mach das in der letzten zeit immer manuel von der github seite. der Update Manager kriegt immer Fehler permission denied und ich hab mich noch net um die rechte gekümmert xD

**Comment by Gutz-Pilz** [comment]
dann mach mal ein update. momentan läuft alles gut :)

**Comment by must4rd** [comment]
hab ich eig vor 2 stunden ca.

**Comment by Gutz-Pilz** [comment]
okay. 
hast du meine addons auch auf dem neuesten stand ?

**Comment by must4rd** [comment]
ok hab den fehler heute morgen wieder 100 mal gesehen und das update gemacht und das issue erstellt. 
gerade noch mal geguckt...fehler ist weg 
war also umsonst das issue aber danke für deine Mühen. 
Was genau macht jetzt eig TraktFetcher? ist das ne alternative zu hdareaorg.py?

**Comment by Gutz-Pilz** [comment]
ja genau. 
falls du ein Trakt account hast. und dort eine Wunschliste an Filmen führst. werden nur diese filme von der Trakt wathclist auf hdarea hinzugefügt

**Comment by must4rd** [comment]
ok alles klar. Gibt es eigentlich noch eine Möglichkeit, die Pakete von HDArea erst in den Linksammler zu packen anstatt die sofort runterladen zu lassen?

**Comment by Gutz-Pilz** [comment]
klar.
in den einstellungn gibt es 2 möglichkeiten.
"Collector Bewertung" und "Queue Bewertung"

alles zwischen collector und queue wertung kommt in den linksammler
und alles über queue in die warteschlange

**Comment by must4rd** [comment]
ok jetzt wo du es sagst klingt es selbstverständlich xD
Ich danke dir!
