### ISSUE TITLE
Error executing hooks: setPlugin() got an unexpected keyword argument 'section'

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [Gutz-Pilz/pyLoad-stuff#68]
If pyload is started with your newes filebot.py in place and the option 'delete_extracted' activated, it throws the error

    ERROR     Error executing hooks: setPlugin() got an unexpected keyword argument 'section'

I think it's due to line 82.

**Comment by Gutz-Pilz** [comment]
can u try this ?
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/86208e43311d37317eba3d09e2c14b6ee369a2db

**Comment by 1337sup3rh4x0r** [comment]
This worked, thanks for the quick response!
