### ISSUE TITLE
Error executing periodical task: local variable 'storage' referenced before assignment

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [Gutz-Pilz/pyLoad-stuff#69]
After updating my pyload installation (also your plugins) for the first time since a couple of months, I now get:

    DEBUG     ADDON SJ: retrieve got exception, title: some.series.S01E01.quality
    ERROR     ADDON SJ: Error executing periodical task: local variable 'storage' referenced before assignment

upon startup. SJ Plugin fails to work after that.

Is there still some half processed download in the pipe or what is the issue here?

**Comment by Gutz-Pilz** [comment]
Can u try backuping files.db and deleting it.
Than restart pyload tonser if it persists?

1337sup3rh4x0r <notifications@github.com> schrieb am Mo., 9. Nov. 2015 um
07:13:

**Comment by 1337sup3rh4x0r** [comment]
Deleting the entire db did it.
But I don't get why this happened. Removing the mentioned entry in the db file would just result in the same error but then with the previous entry.

Thanks for the hint!
