### ISSUE TITLE
SJ not running

### ISSUE THREAD

**Issue by mcmaxl** [Gutz-Pilz/pyLoad-stuff#70]
335	21.11.2015 12:55:30	INFO	ADDON UpdateManager: pyLoad is up to date!
336	21.11.2015 12:55:30	INFO	ADDON UpdateManager: All plugins are up to date!
337	21.11.2015 12:55:43	ERROR	ADDON SJ: Error executing periodical task: global name 'self' is not defined
338	21.11.2015 12:55:43	INFO	ADDON RestartFailed: Restarting all failed downloads...

reinstalled pyload stable, redownloaded all the plugins...still not working. Any ideas?

**Comment by crack00r** [comment]
Same here
https://www.dropbox.com/s/l2rg8b8vwim5ctq/Screenshot%202015-11-23%2000.13.16.png?dl=0

**Comment by b2un0** [comment]
backup the "files.db" in your ~/.pyload/ folder and delete them, restart pyload.

**Comment by mcmaxl** [comment]
Thanks for the suggestion. Still same error, however

**Comment by mcmaxl** [comment]
I did have one download in the queue, it's gone, as expected. Does this affect SJ hook though?

**Comment by b2un0** [comment]
no, but the files.db file contains all your active downloads and queued files.
also this files contains the internal storage where SJ store already added files.

**Comment by crack00r** [comment]
deleteing files.db didnt help for me

**Comment by mcmaxl** [comment]
Andy Progress on this?

**Comment by Gutz-Pilz** [comment]
did u try deleting files.db ?

**Comment by mcmaxl** [comment]
Using python 2.7.9

**Comment by mcmaxl** [comment]
@crack00r any progress on this?

**Comment by crack00r** [comment]
yes, i switch back to jdownloader, and get everything working here :)

**Comment by mcmaxl** [comment]
lol, not the fix i am hoping for. It just so strange how that bug appeared out of nowhere, at least for me. did you change anything before it appeared?

**Comment by Gutz-Pilz** [comment]
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/5fad0cc2a21350b6c1f5fb8af1cbd9ad4f673bc5#diff-b8644aa213553f7092b2aa5ef0e8d996

^^gehts mit der neuesten pyload version und meiner neusten hook version?

**Comment by mcmaxl** [comment]
grad alles auf den neuesten Stand gebracht (immer risky mit pyload...). Leider immer noch die gleiche Fehlermeldung...

**Comment by b2un0** [comment]
SJ.py funktioniert eh nicht mehr, es kann zwar weiterhin folgen zufügen, aber das Captcha lässt sich aktuelle nicht lösen.

Guckst du #77

**Comment by mcmaxl** [comment]
step by step...

**Comment by mcmaxl** [comment]
Now that there is some progress on the captcha issue Id love to get the plugin up and running again. 
Getting this error now: 678	24.02.2016 15:31:20	ERROR	Error executing hooks: 'SJ' object has no attribute 'start_periodical'

**Comment by mcmaxl** [comment]
hat denn jmd das gleiche Problem oder läuft es sonst bei jedem? Hätte jemand vielleicht eine funktionierende version die ich ausprobieren könnte?

**Comment by sveni-lee** [comment]
SJ läuft bei mir wieder....
ich habe einen fresh install gemacht aber du kannst erst einmal folgendes probieren...

> git clone https://github.com/Gutz-Pilz/pyLoad-stuff.git

danach die SJ Datei in den Hook ordner verschieben...
ich habe auch die plugin.conf gesichert und gelöscht und danach neu aufgebaut....

**Comment by mcmaxl** [comment]
hab ebenfalls fresh install gemacht und mir das neueste SJ.py geholt, folgender error:
118	28.02.2016 15:56:21	ERROR	ADDON SJ: Error performing periodical task | global name 'self' is not defined

**Comment by mcmaxl** [comment]
nachdem ich nun die plugin.conf gelöscht habe, bekomme ich keine Fehlermeldung mehr, allerdings scheint SJ.py auch nicht nach neuen Folgen zu schauen. Auch im Debug log gibts keine einzige Meldung zu SJ
