### ISSUE TITLE
HD-Area

### ISSUE THREAD

**Issue by crack00r** [Gutz-Pilz/pyLoad-stuff#71]
Beim laden den Plugins bekomme ich:

23.11.2015 00:26:14 DEBUG     Redirected import module.plugins.hooks.HDAreaOrg -> userplugins.hooks.HDAreaOrg
23.11.2015 00:26:14 ERROR     Error importing HDAreaOrg: No module named contextlib

**Comment by crack00r** [comment]
https://github.com/Gutz-Pilz/pyLoad-stuff/blob/f2da22382ccd6469adfe8bc5d94ebcc8ccd0ea15/SJ.py

This old version works :)

**Comment by Gutz-Pilz** [comment]
oben redest du doch aber von Hdarea. im 2ten kommentar aber von SJ
