### ISSUE TITLE
ADDON SJ: Error performing periodical task | nothing to repeat

### ISSUE THREAD

**Issue by FuX-STV** [Gutz-Pilz/pyLoad-stuff#72]
16	25.11.2015 17:42:40	INFO	ADDON UpdateManager: pyLoad is up to date!
17	25.11.2015 17:42:40	INFO	ADDON UpdateManager: All plugins are up to date!
18	25.11.2015 17:42:56	ERROR	ADDON SJ: Error performing periodical task | nothing to repeat

pyload ist aktuell

Die Stable Version habe ich bereits neu installiert.. file.db auch schon gelöscht, leider ohne Erfolg :-(

**Comment by Gutz-Pilz** [comment]
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/5fad0cc2a21350b6c1f5fb8af1cbd9ad4f673bc5#diff-b8644aa213553f7092b2aa5ef0e8d996
dürfte damit gelöst sein ?
