### ISSUE TITLE
Error executing hooks: 'SJ' object has no attribute 'start_periodical'

### ISSUE THREAD

**Issue by rix1337** [Gutz-Pilz/pyLoad-stuff#74]
Hi,

seit den Updates um Weihnachten läuft SJ ins Leere, der Eventmapper scheint die Funktionsweise des Scripts nicht abzudecken..

```31.12.2015 15:22:44 ERROR Error executing hooks: 'SJ' object has no attribute 'start_periodical```

**Comment by Gutz-Pilz** [comment]
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/76d2413dc53278897fb6b851f22383476bc53ef8#diff-b8644aa213553f7092b2aa5ef0e8d996
Dürfte jetzt wieder klappen. 
Bitte testen und berichten :)

**Comment by Gutz-Pilz** [comment]
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/5fad0cc2a21350b6c1f5fb8af1cbd9ad4f673bc5#diff-b8644aa213553f7092b2aa5ef0e8d996

^^war doch noch nicht komplett - bitte 2.8 benutzen :)

**Comment by rix1337** [comment]
Danke und einen guten Rutsch!

**Comment by J-Ha** [comment]
Selbes Problem wie rix, Error executing hooks: 'SJ' object has no attribute 'get_config'
