### ISSUE TITLE
Error executing hooks: 'SJ' object has no attribute 'get_config'

### ISSUE THREAD

**Issue by J-Ha** [Gutz-Pilz/pyLoad-stuff#75]
Frohes neues und Danke erstmal an Gutz, für deine tollen plugins, nach dem fix von 
'SJ' object has no attribute 'start_periodical'

habe ich nun folgenden bug :
Error executing hooks: 'SJ' object has no attribute 'get_config'

**Comment by Gutz-Pilz** [comment]
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/bc9b227bea31d8bc498bf69adcb8d2fa5d30f5dc

^^probier das mal, bitte

**Comment by J-Ha** [comment]
So mittel, 
723	01.01.2016 16:27:46	DEBUG	ADDON SJ: plugin.db.retrieve got exception, title: Crxxxx.MixxxxS11E01.German.DL.Dubbed.WEBRip.x264-xxxxx
724	01.01.2016 16:27:46	ERROR	ADDON SJ: Error performing periodical task | local variable 'storage' referenced before assignment

kleine bitte / tipp, importier doch json lieber so, so ist es auch abwärtskompatibel bis python 2.5, 
try:
    import simplejson as json

except ImportError:
    import json

**Comment by Gutz-Pilz** [comment]
alles klar. verschiebe mal files.db und starte pyload neu.
dein json fix werd ich gleich importieren!
bin halt auch nur ein scriptkiddie und hab mir python selbst drauf geschafft

**Comment by J-Ha** [comment]
ich hab die files.db schon verschoben, selbes problem, leider.

bin ich auch nur durch zufall drauf gekommen, hab ich irgendwo anders mal gelesen, man lernt nie aus, grad nicht was python angeht.

**Comment by Surio89** [comment]
FileBot hat ebenfalls das "object has no attribute 'get_config'" Problem.
