### ISSUE TITLE
Error executing hooks: 'FileBot' object has no attribute 'config'

### ISSUE THREAD

**Issue by raidyne** [Gutz-Pilz/pyLoad-stuff#76]
Hi,

unfortunately i get the following error starting pyload:
ERROR	Error executing hooks: 'FileBot' object has no attribute 'config'

**Comment by b2un0** [comment]
your pyLoad default plugins are out of date.

**Comment by raidyne** [comment]
thanks! redownloading stable.zip and cleaning .pyload config folder did the trick. 

but it is EXTREMELY annoying that pyload gets corrupt all the time. had to reinstall it nearly 20 times last year.

**Comment by sveni-lee** [comment]
@b2un0

**Comment by b2un0** [comment]
@sveni-lee 
lad dir von hier das Repo als ZIP Runter
https://github.com/pyload/pyload

Und überschreib dann nur den Inhalt des ``modules/plugins`` Ordner mit deinem ``~/.pyload/userplugins/`` Ordner (man sieht ja das die Ordner Struktur gleich ist).

Das funktioniert (eigentlich) Reibungslos.

**Comment by sveni-lee** [comment]
@b2un0 
hab ich jetzt gemacht, Fehler bleibt aber der Selbe....

**Comment by bambuleee** [comment]
Selbes Problem bei mir. Neue Pyload Installation.
