### ISSUE TITLE
Make use of FileBot extraction

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [Gutz-Pilz/pyLoad-stuff#78]
As the pyload extraction plugin is currently broken, would it work to make use of the FileBot extraction argument?

Is it as simple as changing line 176 in your script?

        args.append('skipExtract=y')

to

        args.append('skipExtract=n')

**Comment by b2un0** [comment]
yes, it is.
but this doesn't work with password protected archives.

**Comment by 1337sup3rh4x0r** [comment]
I just tried, it does. Completed rar file and it was extracted and processed correctly. So for non-pw protected files this does the job!

**Comment by Gutz-Pilz** [comment]
that'd cause to much problems for other users. so i keep it as it is.
