### ISSUE TITLE
QNAP Filebot Hook Anleitung

### ISSUE THREAD

**Issue by Loader23** [Gutz-Pilz/pyLoad-stuff#79]
Hi,

nicht wirklich ein Issue aber wusste nicht wohin sonst damit.^^

Gibt es noch eine gute Anleitung für Noobs um den Filebot Hook zum laufen zu bringen? Das Pyload Forum ist ja nun schon länger down und die Einstellungsmöglichkeiten des Hooks sind ja sehr umfangreich. Pyload läuft bei mir auf einer QNAP NAS und ich hoffe, mir kann hier jemand ein paar Tipps geben :-) Danke im Voraus.

**Comment by b2un0** [comment]
Die Einstellungen im Plugin sind 1zu1 die hier
https://www.filebot.net/forums/viewtopic.php?t=215

**Comment by Loader23** [comment]
OK, jetzt gibt es aber das Problem das ich doof bin :D 
Was gebe ich denn bei Filebot executable an, muss ich da die .exe eintragen? Weil das könnte bei einer NAS die auf Linux baut ein Problem sein. Und wo definiere ich das Benennungsschema?
Ich weiß halt nicht, was ich alles in die Felder eintragen muss und dein Link ist leider nicht wirklich auf den Hook anwendbar.

**Comment by b2un0** [comment]
Na du musst erstmal FileBot auf deinem NAS installieren, like this;
https://www.filebot.net/forums/viewtopic.php?t=2335

Der Link ist sehr wohl auf den Hook anwendbar da die Parameter Optionen aus dem Link die Felder im FileBot Hook sind - ich hab den Hook ja initial mit entwickelt ;)

Das Schema definierst du unter "movies/series destination"

so sieht das bei mir unter Linux aus:

![image](https://cloud.githubusercontent.com/assets/2155498/12452756/65c583ba-bf90-11e5-8d64-e7ac0238a85c.png)

**Comment by Loader23** [comment]
Die globale Verfügbarkeit ist wahrscheinlich das Problem, denn ipkg unterstützt QNAP nicht und ein eigenes Paket gibt es nicht. Rednoah schreibt ja: Otherwise you can always default the portable package & unpack & symlink to bin & done. Weißt du wie symlink to bin & done genau aussehen muss? Dein Screenshot ist schonmal eine große Hilfe, vielen Dank dafür.

**Comment by b2un0** [comment]
Du wirst ja das Package irgendwo hin entpackt haben, dort sollte auch eine "filebot.sh" liegen.
Dieser gibst du erstmal ausführbare rechte mittels ``chmod +x filebot.sh`` und führst die dann mittels ``./filebot.sh -version``, entweder du bekommst jetzt ne Fehlermeldung oder die FileBot Version.

Danach können wir über Symlinks reden.

**Comment by Loader23** [comment]
So, habe ich gemacht und hat funktioniert. Habe die Portable Version runtergeladen und FileBot 4.6.1 wird mir angezeigt wenn ich ./filebot.sh -version eingebe. Und wie kann ich jetzt Pyload sagen, dass es das gibt? :-)

**Comment by b2un0** [comment]
Gib in der Hook Konfiguration unter ``filebot executable`` den vollständigen Pfad inkl Dateiname zur filebot.sh Datei an, z.B. so ``/root/filebot/bin/filebot.sh``.
Dann sollte das schon funktionieren.

**Comment by Loader23** [comment]
Jetzt wollte ich das mal ausprobieren und dann sagt mir pyload:
	Error importing FileBot: No module named Addon
Was wahrscheinlich an meiner pyload installation liegt die ich nicht update weil dann wieder 1000 andere Sachen nicht richtig funktionieren.^^ Gibt es eine Version von Filebot, die nicht Addon benötigt oder kann ich Addon einzeln "nachrüsten" ohne das alles andere nicht mehr einwandfrei funktioniert?

**Comment by b2un0** [comment]
Du kannst die hier probieren, da wird noch ``Hook`` importiert statt ``Addon``
https://github.com/Gutz-Pilz/pyLoad-stuff/blob/159789c97a8507aeb6b1801dc533a10f0e9c5a48/FileBot.py

**Comment by Loader23** [comment]
Hmm, dann bekomme ich die Meldung No module named Hook... mein Pyload scheint älter zu sein als ich dachte...

**Comment by b2un0** [comment]
Wenn du nicht mal "Hook" hast wird es kritisch.. selbst die erste Version basiert auf dem "Hook" Plugin als Basis.
Du kannst versuchen das Hook Plugin aus einem alten pyLoad raus zu nehmen und bei dir einfach so rein zu packen.. musst halt Glück haben und die richtige Version erwischen..

**Comment by Loader23** [comment]
Also ich habe ja Hook, nur halt irgendwie anders.^^ In meinem SJ Plugin steht es so:
from module.plugins.Hook import Hook 
und in der Filebot1.0 steht es so:
from module.plugins.internal.Hook import Hook
das internal zu löschen funktioniert aber leider auch nicht.^^

**Comment by b2un0** [comment]
wenn du 
``from module.plugins.internal.Hook import Hook``
in
``from module.plugins.Hook import Hook``
änderst solltest es aber eigentlich funktionieren wenn deine SJ.py damit auch funktioniert (Was sie ja gar nicht mehr dürfte dank NoCaptcha und #77)

**Comment by Loader23** [comment]
Also das SJ funktioniert natürlich nicht mehr so wie früher aber das hinzufügen und automatische E-Mail versenden funktioniert noch, was ich sehr praktisch finde. 
Wenn ich das internal löschen, sagt er mir:
Error executing hooks: 'FileBot' object has no attribute 'pyload'

**Comment by sveni-lee** [comment]
kurze Frage, meinst Du den Log im Webif oder hat du Pyload im Debug mode gestartet?

**Comment by Loader23** [comment]
Log im normalen Webinterface ohne Debug.

**Comment by sveni-lee** [comment]
da siehst Du nicht alle Fehler... kanst du pyload mal mit pyLoadCore -d starten und den log dort beobachten? eventuell zeigt der mehr...

**Comment by Loader23** [comment]
Ok ich verstehe es nicht. Pyload ist bei mir über Entware installiert damit auch der autostart und sowas einfach funktioniert. Wenn ich jetzt in putty den Befehl eingebe 
pyload --daemon --configdir=/opt/var/pyload
Startet Pyload und sogar Filebot funktioniert wunderbar (endlich ein Fortschritt :-) )
Wenn ich allerdings das mitgelieferte Start Script ausführe indem genau der gleiche Befehl ausgeführt wird, wird Filebot einfach nicht ausgeführt... bin da etwas ratlos...

**Comment by b2un0** [comment]
Wird das übliche sein, ``java`` ist wahrscheinlich nicht im pyLoad Kontext auffindbar.

was gibt dir ``whereis java`` auf deinem System aus?

**Comment by Loader23** [comment]
Mit whereis kann QNAP als command leider nichts anfangen. Ist aber das offiziele Java aus dem QNAP Appstore, falls das hilft.

**Comment by Loader23** [comment]
Habe eigentlich noch auf eine Antwort gewartet aber naja, Problem ist ja grundlegend gelöst^^. Also nochmals vielen Dank für die Unterstützung :-)

**Comment by b2un0** [comment]
> Schön wäre es, wenn man Filme aus dem Check rausnehmen könnte aber vielleicht funktioniert das ja in einer neueren Version? 

Wie Filme raus nehmen?!

> Und wisst ihr, warum manche Serien nicht richtig erkannt werden? Über putty funktioniert es einwandfrei und mit pyload wird aus ncisno das normale ncis. Liegt es an der alten Version oder ist das bei euch auch so?

Vergleich deine Kommandozeilen Argumente, da muss es n Unterschied geben wenn es über SSH funktioniert und über pyLoad getriggert nicht.

Am wichtigsten ist das der Zielpfad im pyLoad genau so heißt wie das Release da FileBot den Ordner wo die Datei drin liegt ebenfalls fürs matching verwendet (Die Dateinamen sind ja oft nicht Aussagekräftig).

**Comment by Loader23** [comment]
Ich meinte damit die Film Erkennung ansich, ist aber auch nicht mehr so dramatisch, habe es durch die Argumente lösen können.

Ich habe es nochmal getestet: Über SSH habe ich den Befehl eingegeben:
filebot -rename /share/Daten/Test/ -non-strict --format "{n} {s00e00} - {t}" --lang de
und in pyLoad habe ich das:
/share/CACHEDEV1_DATA/Serien/{n}/{'Staffel '+s.pad(2)}/{n} {s00e00} - {t}
Über SSH funktioniert es wie gesagt ohne Probleme. Und der Ordner in dem die Datei liegt heißt in diesem Beispiel sogar nur Test.

**Comment by b2un0** [comment]
Wenn du im pyLoad das debug log anmachst und dann FileBot triggern lässt sollte im debug Log von pyLoad die ganze Zeile samt aller Argumente mit welcher FileBot durch pyLoad ausgeführt wurde aufgeführt werden..

Aber wenn es jetzt funktioniert ist ja alles in Ordnung ;)

**Comment by Loader23** [comment]
Nene, also die Erkennung der Serien funktioniert nur über SSH richtig, obwohl die eingestellten Parameter die gleichen sind. Auch im Debug Modus über SSH wird mir nicht mehr im Log angezeigt als sonst. Nur halt die Parameter die ich eingestellt habe. 

Vielleicht liegt es einfach an der Serie^^ Das gleiche Problem hatte ich schon mit dem EpisodeMover Plugin, der hat sogar viel unzuverlässiger gearbeitet und manches gar nicht erkannt. Von daher ist das schon eine große Verbesserung. Vielleicht liegt es auch am alten Plugin, sobald eine neuere version von pyLoad wieder zuverlässig funktioniert werde ich es einfach damit nochmal testen.

Also sofern du nicht noch eine zündende Idee hast, ist das alles nicht so schlimm. Grundsätzlich funktioniert alles, also nochmals vielen Dank für die Hilfe :-)
