### ISSUE TITLE
Series download from movieblog or other site

### ISSUE THREAD

**Issue by namealwaysinuse** [Gutz-Pilz/pyLoad-stuff#82]
Hallo Gutz-Pilz,

sag mal gibt es nicht die Moeglichkeit die Serien einfach von einer anderen Seite zu grabben?

Gruesse

**Comment by feuerwasser85** [comment]
Schau mal bei sapbrannigan, der hat eines für movieblog serien, allerdings nur bis pyload ~01.2015

**Comment by b2un0** [comment]
@feuerwasser85  Link bitte? ich finde dazu nichts.

**Comment by namealwaysinuse** [comment]
tatsache vor zwei tagen! https://github.com/zapp-brannigan/own-pyload-plugins

**Comment by Gutz-Pilz** [comment]
Gibts denn ne deutsche seite, die sowas hat?
namealwaysinuse <notifications@github.com> schrieb am Do., 11. Feb. 2016 um
11:50:

> tatsache vor zwei tagen!
> https://github.com/zapp-brannigan/own-pyload-plugins
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gutz-Pilz/pyLoad-stuff/issues/82#issuecomment-182807786>
> .
>
-- 
- von unterwegs -

**Comment by feuerwasser85** [comment]
ja, http://www.movie-blog.org/category/hd-serien/
Nur bei Weitem nicht so übersichtlich wie serienjunkies.org.
Theoretisch hat ja auch HD-Area.org Serien, aber immer zusammengefasst und dann auch schnell wieder offline.

**Comment by b2un0** [comment]
Ich pass das MovieBlogSerien Plugin heute Abend mal auf Basis des SJ.py von @Gutz-Pilz  für die aktuelle pyLoad Version an und teste es. das sollte relativ unkompliziert sein.

**Comment by namealwaysinuse** [comment]
*wieso gibt es hier keinen verneigenden smiley... rummecker* Danke =)

**Comment by feuerwasser85** [comment]
Von mir auch schonmal ein riesen Danke!

**Comment by Pulper** [comment]
Hört sich gut an, mal schauen was daraus wird :-)

**Comment by b2un0** [comment]
Ich habe das hier nicht vergessen, nicht wundern bitte.. hab momentan unerwartet viel um die Ohren.
ich guck mal das ich meinen aktuellen State heute noch in mein Repo pushe.

**Comment by b2un0** [comment]
in meinem Repo ist erstmal eine hoffentlich funktionierende Version, da sind aber noch Anpassungen notwendig.
https://github.com/b2un0/pyload-hooks

**Comment by feuerwasser85** [comment]
Habs gleich ausprobiert.
![image](https://cloud.githubusercontent.com/assets/10442073/13053202/7e0c53d6-d403-11e5-86aa-e7d98f24a819.png)
ERROR ADDON MovieblogSerien: Error performing periodical task | need more than 1 value to unpack

**Comment by b2un0** [comment]
@feuerwasser85 hatte ich auch, dann stimmt deine input-serien.txt nicht
Du darfst nicht (!) die SJ.txt nehmen die du vorher hattest.

**Comment by feuerwasser85** [comment]
wie muss die aufgebaut werden? Gib mal ein Syntax-Beispiel.
.deutsch.*iZombie.*1080p.*DD5.?1.*
.englisch.*Family.Guy.*1080p.*DD5.?1.*
so ist es jetzt bei mir aufgebaut.

**Comment by b2un0** [comment]
@feuerwasser85 Scroll in meinem Repo bitte runter, da steht wie.

**Comment by feuerwasser85** [comment]
sorry, zu schnell drübergelesen. Find ich ne gute Herangehensweise, zuerst die Serie zu fetchen und dann die darin enthaltenen Folgen.
Die Logik der SJ.py war da (sorry) etwas komfortabler, da man ganz allgemein die Serie angegeben hat und es wurde staffelübergreifend gefetchet. Wenn man einen bestimmten Release haben wollte konnte man einfach die Endung mit anhängen zB. .*-TVS

**Comment by feuerwasser85** [comment]
South.Park.S19E01.Umwerfend.und.mutig.GERMAN.DUBBED.DL.1080p.WebHD.x264-TVP,South.Park.S19E.*-TVP
damit müsste er aber was finden.
ERROR	ADDON MovieblogSerien: Nichts gefunden!

**Comment by b2un0** [comment]
Ja, weil kein SO Links bei dem Release vorhanden sind ;)

**Comment by feuerwasser85** [comment]
sind schon vorhanden. Mirror 3 und bei dem anderen release Mirror 2

**Comment by b2un0** [comment]
Guck dir bitte noch mal genau an wie der Syntax der Input-Datei auszusehen hat.

**Comment by feuerwasser85** [comment]
Mit `Arrow.S04.German.Subbed.720p.HDTV.x264-K-O-K,Arrow.S04E.*-K-O-K`
`INFO ADDON MovieblogSerien: NEW EPISODE: Arrow.S04E12.GERMAN.SUBBED.720p.HDTV.x264-K-O-K
INFO Added package Arrow.S04E12.GERMAN.SUBBED.720p.HDTV.x264-K-O-K containing 0 links`

**Comment by b2un0** [comment]
Kein Plan was du da machst, bei mir funktioniert das aktuell genau so wie die `SJ.py`.
Allerdings hat `MB` relativ wenig Serien, hängt von Updateinterval stark hinterher und verwendet bei vielen Links mittlerweile auch `filecrypt.cc` - dort haben wir ja ebenfalls `NoCaptcha` oder `KeyCaptcha` welche beide in pyLoad noch immer nicht supported werden (weswegen ja `SJ.py` ebenfalls nicht funktioniert)..

Teufelskreis :-1:

**Comment by namealwaysinuse** [comment]
Sag ja... Mit jdownloader wäre uns allen geholfen... Links in eine Datei schreiben lassen crawljob und fertig ^^

Von meinem iPhone gesendet

**Comment by b2un0** [comment]
Ich für meinen Teil würde JDownloader sofort headless auf meinem NAS verwenden wenn es ein eigenes, standalone webinterface hätte.. Klar es gibt ne offene API worüber man sich das selber bauen könnte - aber soviel Zeit hab ich dann doch nicht :no_good:

**Comment by namealwaysinuse** [comment]
Nimm doch die myjdownloader Oberfläche die dabei ist? Kann das wichtigste verwalten. 

Von meinem iPhone gesendet

**Comment by b2un0** [comment]
Genau das will ich nicht - geht die n scheiß an was mein JDownloader macht :D
Soll mir auch keiner erzählen das die da gar nichts mit loggen.
Allein die Tatsache das da ne GmbH hinter steckt reicht mir schon ;)

**Comment by namealwaysinuse** [comment]
Und du glaubst pyload ist da anders? Die schicken deine Daten zum Updateabgleich da hin ^^ 

Von meinem iPhone gesendet

**Comment by b2un0** [comment]
Ja, weiß ich ;) aber lassen wir diese Grundsatzdiskussion besser an der Stelle - dafür ist das Ticket ja nicht da. Wir müssen warten bis pyLoad Captcha mit interaktiven Abfragen unterstützt.

**Comment by namealwaysinuse** [comment]
Die bekommen ja nicht mal Ihre Webseite zum laufen ^^

Von meinem iPhone gesendet

**Comment by Leonderi** [comment]
weswegen nutzt ihr movie-blog und nicht hd-world? das page layout ist das gleiche, nur scheinen dort mehr folgen online zu sein...

**Comment by b2un0** [comment]
@Leonderi 
hab HDWorld mal probiert, siehe hier
https://github.com/b2un0/pyload-hooks/blob/master/HdWorldSerien.py
aber die machen immer n redirect auf "anmeldung.domain.tld".
Nehme an das die noch irgend n Cookie o.ä. abfragen (UserAgent hab ich schon getestet).

**Comment by Leonderi** [comment]
Ich steig da leider nicht durch... leider kein plan von python und der gleichen...

wie ist denn die Herangehensweise? Das Hook sucht über die Suchfunktion der Seite nach der Serie und sucht dann auf der der Seite der einzelnen Episode nach dem passenden Downloadlink?

Ich will Yahoo Pipes zurück... :D

**Comment by b2un0** [comment]
Genau, es wird erst die Suche ausgeführt, und dann die Links auf der Seite mittels RegEx ermittelt.

**Comment by Leonderi** [comment]
Ich habe kein Plan von Python bzw. von dem was in den Hooks so passiert...

Da ich früher auch schon immer Flexget am laufen hatte (mit Pipes war das echt klasse) habe ich mir nun mal die Flexget RSS generator von Gutz-Pilz angeschaut. 

Mit etwas Gehirnschmalz, Google und viel geteste habe ich es hinbekommen, einen RSS Gernerator für HD-World Serien zu erstellen. Das ganze scheint aktuell recht gut zu laufen. Das Script pickt einfach nur die Titel und die Download links von der Seite.

Eventuell kann man das ganze ja noch verfeinern oder sogar Teile davon verwenden um es in ein hook für pyload zu übernehmen. Hier aufjedenfall der Link dazu: https://github.com/Leonderi/Flexget-RSS-Generator/blob/master/rss-world.py
