### ISSUE TITLE
Error importing HDAreaOrg: invalid syntax (HDAreaOrg.py, line 64)

### ISSUE THREAD

**Issue by lordfiSh** [Gutz-Pilz/pyLoad-stuff#83]
hey, da dein Flexget Script leider auch nicht mehr richtig geht, hatte ich diesen Pyload Hook probiert, jedoch: 
> 13.02.2016 18:44:09 INFO      pyLoad is up and running
> 13.02.2016 18:44:11 DEBUG     RestartFailed: Restart failed downloads
> 13.02.2016 18:45:06 DEBUG     Redirected import module.plugins.hooks.HDAreaOrg -> userplugins.hooks.HDAreaOrg
> /volume1/config/pyload/userplugins/hooks/HDAreaOrg.py:64: Warning: 'with' will become a reserved keyword in Python 2.6
> 13.02.2016 18:45:06 ERROR     Error importing HDAreaOrg: invalid syntax (HDAreaOrg.py, line 64)
> Traceback (most recent call last):
>   File "/volume1/@optware/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
>     plugins[name]["name"])
>   File "/volume1/@optware/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
>     module = __import__(newname, globals(), locals(), [plugin])
>   File "/volume1/config/pyload/userplugins/hooks/HDAreaOrg.py", line 64
>      with contextlib.closing(urlopen(request_url)) as response:
>                    ^
>  SyntaxError: invalid syntax

**Comment by pfloosy** [comment]
Same problem here. Any solutions?

**Comment by Gutz-Pilz** [comment]
These are not maintained anymore.
Pls Check
https://github.com/rix1337/docker-rsscrawler 
along with jdownloader
