### ISSUE TITLE
HDAreaOrg bennen Filme in Genre (Jahr) um

### ISSUE THREAD

**Issue by sveni-lee** [Gutz-Pilz/pyLoad-stuff#84]
Ich habe einen kompletten fresh install gemacht... jetzt läuft sowohl HDAreaOrg als auch SJ wieder...
bei SJ funktioniert auch alles nur bei HDAreaOrg werden die hinzugefügten Filme in Genre (Jahr) umbenannt...

```
6.02.2016 21:48:38 INFO      ADDON HDAreaOrg: COLLECTOR: Drama (2014) IMDb: 6.8
26.02.2016 21:48:38 INFO      Added package Drama (2014) IMDb: 6.8 containing 1 links
26.02.2016 21:48:45 DEBUG     ADDON HDAreaOrg: Drama (2011) already downloaded
26.02.2016 21:48:52 INFO      ADDON HDAreaOrg: COLLECTOR: Animation (2012) IMDb: 8.0
26.02.2016 21:48:52 INFO      Added package Animation (2012) IMDb: 8.0 containing 1 links
26.02.2016 21:49:01 INFO      ADDON HDAreaOrg: COLLECTOR: Action (2015) IMDb: 6.2
26.02.2016 21:49:01 INFO      Added package Action (2015) IMDb: 6.2 containing 1 links
26.02.2016 21:49:10 DEBUG     ADDON HDAreaOrg: Action (2009) IMDb: 3.8: zu SCHLECHT
26.02.2016 21:49:17 DEBUG     ADDON HDAreaOrg: Action (2011) IMDb: 2.2: zu SCHLECHT
26.02.2016 21:49:25 INFO      ADDON HDAreaOrg: COLLECTOR: Biography (2015) IMDb: 8.2
26.02.2016 21:49:25 INFO      Added package Biography (2015) IMDb: 8.2 containing 1 links
26.02.2016 21:49:33 INFO      ADDON HDAreaOrg: COLLECTOR: Crime (2007) IMDb: 6.5
26.02.2016 21:49:33 INFO      Added package Crime (2007) IMDb: 6.5 containing 1 links
26.02.2016 21:49:42 DEBUG     ADDON HDAreaOrg: Drama (2015) already downloaded
´´´

**Comment by feuerwasser85** [comment]
Bei mir schon seit längerem. Denke das soll ein Feature sein, weil die Filme die gefunden werden alle in einem Package zusammengefasst werden. Hätte aber auch wieder lieber einzeln. Man möchte ja doch noch aussuchen :-)
OT: Wie hast du einen fresh install gemacht? Auf welcher Plattform liegt deine Installation?

**Comment by sveni-lee** [comment]
> OT: Wie hast du einen fresh install gemacht? Auf welcher Plattform liegt deine Installation?
ich hab ein git clone https://github.com/Arno-Nymous/pyload.git

und dann... python /dein ordner/pyload/pyLoadCore.py

Ich kann mir nicht vorstellen, das es ein Feature sein soll... Macht ja eigendlich keinen Sinn, weil man ja nicht mehr aussortiren kann....

**Comment by feuerwasser85** [comment]
`SynologyNAS:/# python /opt/pyload/pyLoadCore.py
Traceback (most recent call last):
  File "/opt/pyload/pyLoadCore.py", line 48, in <module>
    from module.network.RequestFactory import RequestFactory
  File "/opt/pyload/module/network/RequestFactory.py", line 22, in <module>
    from Browser import Browser
  File "/opt/pyload/module/network/Browser.py", line 6, in <module>
    from HTTPRequest import HTTPRequest
  File "/opt/pyload/module/network/HTTPRequest.py", line 20, in <module>
    import pycurl
ImportError: No module named pycurl`

**Comment by sveni-lee** [comment]
Also Ich hab's nach [dieser Anleitung](https://wiki.debianforum.de/PyLoad) gemacht...

**Comment by sveni-lee** [comment]
ich habe mir das Addon mal angesehen aber ich sehe nicht warum das jetzt die genres anstatt der Namen ausgibt... Ich kann mir nur vorstellen das sich etwas an der Seite geändert hat....

**Comment by sveni-lee** [comment]
Ich habe mir das ganze noch einmal angesehen... der Ausdruck im log und im "Linksammler" von pyload wird ja hier erzeugt

´´´
self.log_info("COLLECTOR: "+title.decode("utf-8")+" ("+year+") IMDb: "+rating)
self.pyload.api.addPackage(title.decode("utf-8")+" ("+year+") IMDb: "+rating, dlLink.split('"'), 0)
self.items_to_collector.append(title.encode("utf-8")+" ("+year+")\nIMDb: "+rating+"  ||  Info: "+make_tiny(imdb_url)) 
```
wenn ein Titel abgelehnt wird weil es schon gefetched wurde sieht der Ausdruck für das log so aus

´´´
self.log_debug(title+ " already fetched")
```
also kann es für meine Begriffe nur noch an titke.decode liegen...

**Comment by sveni-lee** [comment]
So also ich habe das Problem gefunden... Zeile 146
```
orig_title = imdb_site.find("span", {"class" : "itemprop"}).getText()
´´´
ich denke IMDB hat seinen seiten aufbai geändert, von dort holt sich das Plugin den original Titel.

ich ha es jetzt mal wie folgt angepasst:
```
orig_title = imdb_site.find("h1", {"itemprop" : "name"}).getText()
´´´
alsdings bekomme ich dann diesen Ausdruck

> The Corridor&nbsp;
resultiert hierraus
```
<h1 itemprop="name" class="">The Corridor&nbsp;
´´´
weiß jemand wie ich python dazu bewegen kann den Teil "&nbsp;" wegzulassen?

**Comment by DieNrSieben** [comment]
Ich habe es so 
`orig_title_ = imdb_site.find("h1", {"itemprop" : "name"}).getText() 
orig_title = unicode.join(u'',map(unicode,orig_title.replace("&nbsp;", ""))) 
`

gelöst
