### ISSUE TITLE
wie ladet ihr denn jetzt?

### ISSUE THREAD

**Issue by h00re1337** [Gutz-Pilz/pyLoad-stuff#87]
Hey,

ich bin seit knapp nem jahr von pyload zu JD2 gewechselt weil der captchas nicht mehr entschlüsselt werden konnten. heute hab ich mir nochmal pyload installiert und gemerkt das es immer noch nciht geht.

daher die frage wie laded ihr automatisiert eure serien runter? mit jd gibts ja nur die möglichkeit mit flexget aber das hab ich bisher noch nicht hinbekommen

**Comment by b2un0** [comment]
JD2 headless mit Fileboot Event, SJ geht auch mit JD2 im headless Mode
nicht daher bringt dir auch flexget nichts.
Ich nutz flexget nur als notifier, adden muss ich dann selber per click n
load.

**Comment by h00re1337** [comment]
genau das funzt ja auch alles per click and load. aber ist mir zu lästig möchte es alles automatisiert adden lassen

**Comment by b2un0** [comment]
finde ne andere Seite als SJ wo du die liste der aktuell neu hinzugekommenen Episoden pro Serie bekommst und wo nicht ReCaptcha2 verwendet wird.
Das Problem ist ja ReCaptcha2 welches nicht mehr so einfach gelöst werden kann.

**Comment by Gutz-Pilz** [comment]
rsscrawler von rix1337
https://github.com/rix1337/RSScrawler

**Comment by must4rd** [comment]
ich lade immer noch über pyload weil das bei mir auf der nas installiert ist... das SJ plugin added immer noch die einzelnen Folgen und ich hab ne click and load weiterleitung eingerichtet...man muss lediglich den link einmal im browser kopieren und das captcha lösen... einfacher für mich weil filebot das automatisch sortiert und ich den Rechner nicht anlassen muss :-) schade das es net mehr automatisch geht aber 2-3 clicks pro Folge ist auch net die Welt xD
